### ISSUE TITLE
pkg_functions

### ISSUE THREAD

**Issue by jimhester** [r-lib/pak#1]
- [x] pkg_install(“sf”) # install from cran without prefix
- [x] local_pkg_install() - pkgdepends does not currently work with directories. pkginstall does, but we need to also query / install the dependencies.
- [x] local_pkg_install_deps()
- [x] local_pkg_install_dev_deps()
- [x] pkg_update() # default updates all packages 
- [x] pkg_remove()
- [x] pkg_status()

**Comment by Breza** [comment]
I'm really interested in seeing `pkg_update()` become a reality. Multithreading when installing packages is nice, but it would _really_ be a gamechanger when updating dozens of packages at once.

**Comment by jimhester** [comment]
@Breza assuming you are updating packages from CRAN you can already do this with `update.packages(Ncpus = 8)` to update e.g. 8 packages in parallel. Or set `option(Ncpus = XYZ)` to do it by default.

**Comment by gpapo** [comment]
Bump on this to know: is anyone working on the `pkg_update()` functionality yet?

**Comment by rossellhayes** [comment]
Can `pkg_update()` be implemented as `pkg_install(rownames(utils::old.packages()))`?

**Comment by gaborcsardi** [comment]
@rossellhayes Only if all your installed packages are available on CRAN/Bioc and your configured repos. If you have other package sources, then it gets more difficult. Updating the whole library is not a trivial operation.

**Comment by rossellhayes** [comment]
I hadn't considered that, thank you for explaining!

**Comment by gaborcsardi** [comment]
#289 has `pkg_upgrade()`, which upgrades one package and its dependencies.
