### ISSUE TITLE
A Windows story

### ISSUE THREAD

**Issue by jennybc** [r-lib/pak#126]
Recounting what just happened to me on my Windows VM. Perhaps there's something useful in here re: user behaviour.

Overall goal was to install the dev version of googledrive. I deliberately leave my R setup on Windows in a rather primitive state in order to experience how lots of people live.

Successful call to `usethis::create_from_github("tidyverse/googledrive")`.

Immediately try to check. Fail because don't have dev deps. Use `install.packages("devtools")`to make sure devtools is installed and current. Successful.

`devtools::install_dev_deps()`. Get the menu re: "these packages have more recent version available". I say "update all".  These  are all upgrades of CRAN packages.

All succeed except backports. Get the dreaded "cannot remove prior installation" message.

I install pak from CRAN. That works. I attempt both `pak::pkg_install("backports", upgrade = TRUE)` and `pak::pkg_install("backports")`. Both fail in same way.

![backport-failure](https://user-images.githubusercontent.com/599454/56844426-d751ee80-6864-11e9-91ea-c6396d836ddc.PNG)

Here is the actual screwed up state of backports:

![backports-library-situation](https://user-images.githubusercontent.com/599454/56844433-eafd5500-6864-11e9-9cc7-3d2d07883f6d.PNG)

This dll is the **only** file that exists (deep) below the backports directory in my library.

Perhaps the lesson here is that, had I used pak from the start, I would never have ended up in this [splinched state](https://harrypotter.fandom.com/wiki/Splinching). And I can sort it out. Consider this a report from the field in case pak can help people recover from this sort of dysfunctional initial state.

**Comment by Hong-Revo** [comment]
The reason for this long-time problem is that on Windows, loading a dll into memory also locks the file on disk. You can only delete the dll after unloading it. Because of this, trying to remove the package will fail if it contains any compiled code.

Normally Win applications will unload dlls when they're done with them, but R doesn't do so (probably because unloading packages wasn't planned for from the start, and is still very hacky), I'm not sure if fixing this is within pak's scope.

**Comment by jennybc** [comment]
> The reason for this long-time problem is that on Windows, loading a dll into memory also locks the file on disk ...

I know. I am just reporting problems I have experienced as an issue.

And yes improving these dysfunctional Windows situations is part of what pak is meant to address.

**Comment by gaborcsardi** [comment]
This should be all fixed now, with pak detecting locked DLLs, unload packages and terminating other R processes, as needed/requested.
