### ISSUE TITLE
error intalling package.

### ISSUE THREAD

**Issue by jjesusfilho** [r-lib/pak#130]
I got the following error during installation:

Failed to download styler from `https://cran.rstudio.com//bin/macosx/el-capitan/contrib/3.6/styler_1.1.1.tgz`

There is a double slash in com//bin.

**Comment by vincentarelbundock** [comment]
FWIW, I get the same problem on an Ubuntu machine.

**Comment by romainfrancois** [comment]
Same.

**Comment by gaborcsardi** [comment]
This could have been the pkgcache update. I see
```r
❯ r <- pak:::remotes()$new("dotenv", lib = "/tmp/lib/")
❯ sol <- r$solve()
ℹ Checking for package metadata updates
✔ All 12 metadata files are current.
✔ Loading session disk cached package metadata
✔ Using cached package metadata

❯ dl <- r$download_solution()
❯ dl$download_error
[[1]]
<async_rejected: headers is not a character vector>

❯ dl$download_error[[1]]$calls
```

```r
...
[[18]]
is_deferred(value)

[[19]]
fun(value)

[[20]]
download_one_of(urls, target, on_progress = on_progress, headers = http_headers)

[[21]]
assert_that(is_character(urls), length(urls) >= 1, is_path(destfile),
    is_path_or_null(etag_file), is.character(headers), all_named(headers))

[[22]]
stop(assertError(attr(res, "msg")))
...
```

and apparently the `headers` argument is `NULL` here. 

Will probably have a quick fix in pak.

**Comment by gaborcsardi** [comment]
I think https://github.com/r-lib/pkgcache/commit/52a9d26bb5f51f11a3b355325a9c5f4ba6e2c672 fixes this, I'll put up a pkgcache release in a minute.

**Comment by gaborcsardi** [comment]
Will fix in pak as well, but a new pak release takes a bit longer....

**Comment by vincentarelbundock** [comment]
after updating `pkgcache` from github it works for me. Thanks!

**Comment by jjesusfilho** [comment]
I still get the error for installations that ask to continue:
``` r
pak::pkg_install("qs", upgrade = TRUE)
>  Checking for package metadata updates
> ✔ Using cached package metadata
> 
> → Will update 1 packages:
>   qs
> 
> → Will not update 2 packages.
> 
> → Will download 1 CRAN packages (2.12 MB).

? Do you want to continue (Y/n) Y

> Error: Failed to download qs from `https://cran.rstudio.com//bin/macosx/el-capitan/contrib/3.6/qs_0.16.1.tgz`.
```

**Comment by gaborcsardi** [comment]
@jjesusfilho make sure you run `pak::pak_setup()` after installing the new version of the pkgcache package.

**Comment by jjesusfilho** [comment]
Thank you, it is working  after `pak::pak_setup()`.
