### ISSUE TITLE
pak/remotes incompatibility

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#133]
```R
pkg_install("r-lib/rlang")
packageDescription("rlang")
#> ...
#> RemoteType: github
#> RemoteHost: api.github.com
#> RemoteRepo: rlang
#> RemoteUsername: r-lib
#> RemoteRef: r-lib/rlang
#> RemoteSha: 25e6f89c66d4229143a190612e02df71f92029d7
#> GithubRepo: rlang
#> GithubUsername: r-lib
#> GithubRef: r-lib/rlang
#> GithubSHA1: 25e6f89c66d4229143a190612e02df71f92029d7
```

which when installing something depends on rlang, this leads to:

```
Error: HTTP error 422.
  No commit found for SHA: r-lib/rlang

  Rate limit remaining: 4991/5000
  Rate limit reset at: 2019-06-25 19:43:57 UTC
```

Whereas remotes creates this:

```R
remotes::install_github("r-lib/rlang")
packageDescription("rlang")
#> ...
#> RemoteType: github
#> RemoteHost: api.github.com
#> RemoteRepo: rlang
#> RemoteUsername: r-lib
#> RemoteRef: master
#> RemoteSha: 25e6f89c66d4229143a190612e02df71f92029d7
#> GithubRepo: rlang
#> GithubUsername: r-lib
#> GithubRef: master
#> GithubSHA1: 25e6f89c66d4229143a190612e02df71f92029d7
```

**Comment by gaborcsardi** [comment]
I can't reproduce the error. AFAICT what happens is that 
- if you installed the package by pak, then remotes will do an unnecessary update of it. You might need a recent version of remotes for this, older versions might chose indeed.
- if you installed the package by remotes, pak is still able to avoid an unnecessary update.

This said, it is indeed desired that the metadata is a same or at least fully compatible. It seems that only `RemoteRef` is different for pak (and `GithubRef` which is the compatibility version of the same thing). So I'll change that to be the same as in remotes, and add a new entry, e.g. `RemotePkgRef` for the originally requested ref. (remotes does not store that anywhere actually.)

**Comment by hadley** [comment]
Ok, I'll let you know if this crops up again.
