### ISSUE TITLE
upgrade a github package only by its name

### ISSUE THREAD

**Issue by cderv** [r-lib/pak#151]
I just stumble on behavior I was not expecting from experiences with remotes.

With `remotes` we can do 
```r
remotes::update_packages("chromote")
```
and it will update a github package if this is the one installed, without explicitly providing `rstudio/chromote`

With `pak`, 
```r
pak::pkg_install("chromote", upgrade = T)
```
does not offer to update the package says nothing about the package. 

However, 
```r
pak::pkg_install("rstudio/chromote", upgrade = T)
```

If this behavior to be explicit differs from `remotes` on purpose, there is nothing here and this can be closed.

**Comment by jimhester** [comment]
I think this would be handled by `pkg_update()`, which doesn't yet exist. I am going to close this issue as it is tracked elsewhere.
