### ISSUE TITLE
pak shouldn't install 2nd copy of recommended packages into user library

### ISSUE THREAD

**Issue by jennybc** [r-lib/pak#154]
I keep base and recommended packages in the default library and everything else in a user library:

``` r
.libPaths()
#> [1] "/Users/jenny/Library/R/3.6/library"                            
#> [2] "/Library/Frameworks/R.framework/Versions/3.6/Resources/library"
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

`pak::pkg_install()` regularly wants to install a second instance of, e.g. recommended packages, into my user library.

Example from today:

``` r
> pak::pkg_install("pkgdown")
ℹ Checking for package metadata updates
✔ All 12 metadata files are current.                                              
✔ Using session cached package metadata                                           
✔ Using cached package metadata                                                   

→ Will install 1 packages:
  MASS
  
→ Will not update 52 packages.

→ Will download 1 CRAN packages (1.18 MB).

? Do you want to continue (Y/n) y
✔ Installed MASS 7.3-51.4  [81ms]                                                 
✔ 1 + 52 pkgs | kept 45, updated 0, new 1 | downloaded 1 (1.18 MB) [4.7s]         
> library(MASS)

Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select

> searchpaths()
 [1] ".GlobalEnv"                                                              
 [2] "/Users/jenny/Library/R/3.6/library/MASS"
...
```

Prior to this MASS was installed, only once, in the default library. And the version was current.

This makes me hesitant to use pak, as it feels like it will gradually install 2nd copies of ?all? the recommended packages into my user library, whereas I'd rather have just one copy, in the default library.

**Comment by gaborcsardi** [comment]
Recommended packages are not special in this respect, only the base packages are (because they cannot change for a given R version). 

pak installs everything but the base/core packages into the same library. This is a strong rule, and it ensures isolation. If a project depends on some version of a package, and another project uses another version of the same package, they interfere if we don't install all dependencies into separate libraries.

**Comment by gaborcsardi** [comment]
Closed by https://github.com/r-lib/pkgdepends/commit/1f3dd6f90466ffc5067d16ebb1702797fd024085
