### ISSUE TITLE
asciicast on pkgdown homepage is a broken link

### ISSUE THREAD

**Issue by cderv** [r-lib/pak#157]
Seen on the website
![image](https://user-images.githubusercontent.com/6791940/67007016-c1700880-f0e6-11e9-938c-09cdd426a8d4.png)

I think the website was not rebuilt correctly after readme modification in 7a69eaa18b7a250d044e9c6e948ff8930823a314
https://github.com/r-lib/pak/blob/00f4bd509a6f9145973b376d9c2bdcea652b0119/README.Rmd#L33-L35
https://github.com/r-lib/pak/blob/00f4bd509a6f9145973b376d9c2bdcea652b0119/docs/index.html#L83

**Comment by jimhester** [comment]
Seems to be fixed now.

**Comment by cderv** [comment]
It is still the same when I go to https://pak.r-lib.org/
![image](https://user-images.githubusercontent.com/6791940/90607261-480ede00-e201-11ea-87d3-ea65bc1847d5.png)

I see that the website is ok in `gh-page`: 
https://github.com/r-lib/pak/blob/62736f64492f622f06b1df7458d3bd1f309fd703/index.html#L88

but there is also a `docs` folder in this repo and the website there has not changed
https://github.com/r-lib/pak/blob/e1d251aecf80d1e6934e2e7c9ed98ddfaa39a92a/docs/index.html#L83

And as you are deploying to branch 
https://github.com/r-lib/pak/blob/e1d251aecf80d1e6934e2e7c9ed98ddfaa39a92a/.github/workflows/pkgdown.yaml#L46

I believe the correct site is the one in gh-page. the `docs` folder is two years old it seems. 

Are you serving the gh-page or the docs folder ? 
Anyway, I may missed something on your workflow for now, but the image still does not show when I connect to the website. 🤷‍♂️

**Comment by jimhester** [comment]
Yeah the homepage for the CRAN release needs to be rebuilt. https://pak.r-lib.org/dev/ is correct.

**Comment by jimhester** [comment]
Ok I fixed the release website as well, thanks for opening the issue!

**Comment by cderv** [comment]
You're welcome! 
Next time I'll do the PR also 😉
