### ISSUE TITLE
Error when trying to install packages with pak

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/pak#173]
Hi,

Just installed `pak` (tried installing from CRAN and also the dev version from GitHub), but either way when I try to install a package:
```r
pak::pkg_install("reticulate") # just an example
```
I receive the following error...
```
x Metadata update failed                                      
Error: callr subprocess failed: Not Found (HTTP 404).
```

Any idea what my issue might be?

**Comment by njtierney** [comment]
Hi there, came here to report this same issue:

``` r
pak::pkg_install("MilesMcBain/dflow")
#> Error: callr subprocess failed: Not Found (HTTP 404).
```

<sup>Created on 2020-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Pretty sure this is due to https://github.com/r-lib/pkgcache/issues/41, it should  be fixed once the bundled pkgcache package is updated.

**Comment by jimhester** [comment]
Seems to be working now that the upstream issue in pkgcache is fixed.
