### ISSUE TITLE
pak::pkg_install() doesn't work but the install.packages() does

### ISSUE THREAD

**Issue by vikram-rawat** [r-lib/pak#191]
I have had this issue with Matrix and haven packages. I am windows. 

![image](https://user-images.githubusercontent.com/22342596/91316456-74fd5b00-e7d6-11ea-887d-757a1c94434e.png)
![image](https://user-images.githubusercontent.com/22342596/91316523-88102b00-e7d6-11ea-9c0e-4f03ca5cb742.png)

**Comment by gaborcsardi** [comment]
You can install the current dev version like this:
```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
```
This should work.

**Comment by vikram-rawat** [comment]
I had this issue downloading Tidyverse. does it mean I should be pointing to a different repo than the one we use?

![image](https://user-images.githubusercontent.com/22342596/91316979-17b5d980-e7d7-11ea-9821-3538e80e51e4.png)

**Comment by vikram-rawat** [comment]
I did and it worked like a charm. Thanks for replying so quickly. Great package!!
