### ISSUE TITLE
Pak installation not working on windows - probably transient error

### ISSUE THREAD

**Issue by richfitz** [r-lib/pak#193]
As seen https://github.com/mrc-ide/pkgbuilder/runs/1037392997?check_suite_focus=true - which ran shortly after a successful build.

I've run on a different windows computer shortly after and I see this set of errors:

```
> install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
Installing package into ‘C:/Users/rfitzjoh/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://r-lib.github.io/p/pak/dev/bin/windows/contrib/3.6/pak_0.1.2.9001.zip'
Content type 'application/zip' length 12063412 bytes (11.5 MB)
downloaded 11.5 MB

files ‘DESCRIPTION’, ‘Meta/package.rds’ have the wrong MD5 checksums

The downloaded binary packages are in
        C:\Users\rfitzjoh\AppData\Local\Temp\RtmpS83AsI\downloaded_packages
> library(pak)
Warning messages:
1: package ‘pak’ was built under R version 3.6.3 
2: In find.package(top_deps) : there is no package called ‘filelock’
3: In find.package(top_deps) : there is no package called ‘pkgcache’
4: In find.package(top_deps) : there is no package called ‘pkgdepends’
5: In find.package(top_deps) : there is no package called ‘pkgsearch’

> pak::pkg_install("mrc-ide/dust")
Private library is embedded, pak is ready to go.
Private library is embedded, pak is ready to go.
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'C:\Users\rfitzjoh\AppData\Local\Temp\RtmpE1qaWO\file69b4415d610\crayon/R/crayon.rdx', probable reason 'No such file or directory'
```

It looks like the bundled library in pak is corrupt on this build? I've downloaded the zipball for this release (md5: d73e832bc640f091c566173081805d00) and the package does appear to contain the missing packages listed above.

**Comment by jimhester** [comment]
I can't reproduce this now, I think it must have been transient.

**Comment by richfitz** [comment]
Thanks for looking - I just verified again, and my windows build on gh-actions still fails (4.0.2) as does my windows 3.6.1 box.

After a little digging I managed to replicate on macOS with this:

```
lib <- tempfile()
dir.create(lib)
.libPaths(lib)
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::pkg_install("r-lib/R6")
```

Failing with

```
Error in find.package(top_deps) : 
  there are no packages called ‘callr’, ‘cli’, ‘crayon’, ‘curl’, ‘desc’, ‘filelock’, ‘glue’, ‘jsonlite’, ‘pkgcache’, ‘pkgdepends’, ‘pkgload’, ‘pkgsearch’, ‘prettyunits’, ‘processx’, ‘ps’, ‘rprojroot’, ‘tibble’, ‘zip’
```

It also looks like pak is failing with this itself on windows at the moment: https://github.com/r-lib/pak/runs/1037843385

**Comment by jimhester** [comment]
Thanks for the reproducible example. I think I have solved the issue, and I kicked off the dev build to fix it, which worked except on macOS https://github.com/r-lib/pak/runs/1042023185?check_suite_focus=true#step:3:459 due to an unrelated bug in `install.packages()` with mixed binary and source packages. So at least the windows and linux builds should be fixed going forwards
