### ISSUE TITLE
The installation progress bar does not show

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pak#199]

**Comment by gaborcsardi** [comment]
Actually, seems fine now with the latest installer.

**Comment by gaborcsardi** [comment]
OTOH, latest pkgdepends does not show it...

**Comment by jimhester** [comment]
It is not supposed to show on CI FWIW

**Comment by jimhester** [comment]
This looks to be fixed with recent pkgdepends updates, https://github.com/r-lib/pkgdepends/commit/7351ce652e30a58152262cb7737794533f681617, https://github.com/r-lib/pkgdepends/commit/c353197d63fa3c9703ef44aeb2d07ba695404bed
