### ISSUE TITLE
Re-license as MIT

### ISSUE THREAD

**Issue by batpigandme** [r-lib/pak#201]
This is part of a general effort to make the licensing across r-lib and tidyverse as simple and consistent as possible.

We've reviewed all non-RStudio employee/contractor contributions, and don't believe any merit a copyright claim (e.g. typo fixes) — https://github.com/r-lib/pak/graphs/contributors.

**Comment by gaborcsardi** [comment]
The binary installer contains copies of other GPL packages, so this is not so simple. We already use this binary to distribute dev pak, and will use it for CRAN pak as well, soon.

In particular, these are the GPL dependencies:
- assertthat
- backports
- digest
- ellipsis
- fansi
- lifecycle
- lpSolve
- parsedate
- pillar
- pkgbuild
- pkgload
- rlang
- rprojroot
- vctrs
- withr

**Comment by batpigandme** [comment]
Thanks, @gaborcsardi.

@hadley, 
I know some of these are changing (e.g. rlang, vctrs, ellipsis…), but are we not changing ones with GPL dependencies?

**Comment by jimhester** [comment]
Also some of these are GPL because they contain GPL'd code from R itself, so cannot change license, e.g. backports and pkgload for sure

**Comment by batpigandme** [comment]
Non-option because bundled version of pak literally includes other packages.

**Comment by hadley** [comment]
We could technically license the pak specific code as MIT and then make it clear that the binary is GPL, but I think that's likely slicing things too thin.
