### ISSUE TITLE
{pak} breaks {remotes}

### ISSUE THREAD

**Issue by pat-s** [r-lib/pak#214]
After installing {pak} via `install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")` on macOS 10.15.7, `remotes::update_packages()` is broken for me because {pak} has a malformed package installation entry.

```r
remotes::update_packages(ask = FALSE)
Error in if (is_tarball) { : argument is of length zero
Calls: <Anonymous> ... vapply -> FUN -> remote_sha -> remote_sha.local_remote
Backtrace:
1: remote_sha.local_remote(x)
2: remote_sha(x)
3: FUN(X[[i]], ...)
4: vapply(remote, function(x) remote_sha(x), character(1))
5: package_deps(packages, repos = repos, type = type)
6: remotes::update_packages(ask = FALSE)
```

<img width="299" alt="image" src="https://user-images.githubusercontent.com/8430564/97760858-7c0d5600-1b04-11eb-9c59-35df6876528b.png">

The image was taken when debugging the error above in the `vapply` stage.

In addition I am unable to install any package with {pak}

```r
pak::pkg_install("devtools")
Error in dyn.load(dll_file) : 
  unable to load shared object '/private/var/folders/wp/vf2dpq8j02xd0pw15rz4qqkm0000gn/T/RtmpZzlZzB/file745779c90902/ps/libs//ps.so':
  dlopen(/private/var/folders/wp/vf2dpq8j02xd0pw15rz4qqkm0000gn/T/RtmpZzlZzB/file745779c90902/ps/libs//ps.so, 6): no suitable image found.  Did find:
	/private/var/folders/wp/vf2dpq8j02xd0pw15rz4qqkm0000gn/T/RtmpZzlZzB/file745779c90902/ps/libs//ps.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/var/folders/wp/vf2dpq8j02xd0pw15rz4qqkm0000gn/T/RtmpZzlZzB/file745779c90902/ps/libs/ps.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Backtrace:
1: dyn.load(dll_file)
2: load_private_package("ps", create = create)
3: load_private_packages(create = create)
4: new_remote_session()
5: restart_remote_if_needed()
6: remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), 
7: pak::pkg_install("devtools")
```

**Comment by gaborcsardi** [comment]
> remotes::update_packages() is broken for me because {pak} has a malformed package installation entry

Well, that's a bug in remotes, I guess. It could ignore the broken installations.

What version of R is this?

**Comment by pat-s** [comment]
R version 4.0.3 Patched (2020-10-27 r79379)

**Comment by pat-s** [comment]
I guess with all the troubles with {pak} I'll just wait until it has reached a stable stable.

The motivation to fix this upstream in {remotes} might be very low given that such a state probably never happened before? (I could not find an issue with the error message at all).
Feel free to report to {remotes} :)

**Comment by gaborcsardi** [comment]
My guess is that you use source packages instead of macOS binaries, because you are not using the CRAN build of R? So you'll ended up with the Linux package, which of course does not work. 

Install like this: 

```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/", type = "mac.binary")
```

**Comment by gaborcsardi** [comment]
Btw. it really helps if you show what exactly you did, including the output.

**Comment by pat-s** [comment]
Why was my comment deleted?

**Comment by gaborcsardi** [comment]
BEcause it was snark, and it did not add anything to the issue at hand.

**Comment by pat-s** [comment]
That's arguably a quite subjective view of yours. 

As a personal consequence I won't report any issues in the future anymore. 

This is a personal statement of mine and does not relate to any organization I am with.

**Comment by gaborcsardi** [comment]
@pat-s Right, it was an overreaction to delete it. So, sorry about it. If it really bothered me, I could have asked you to delete it or update it. But it does not bother me any more.

I believe the issue is #215, and the workaround there or above on this pages solves your problem.
