### ISSUE TITLE
Loaded/locked packages UI improvements

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pak#216]
- [x] Try to work around the lazyload database error.
- [x] Remove the comma.
- [x] RStudio should offer a restart if any packages were unloaded (on all platforms), unless we can work around the lazyload DB error.
- [x] Report packages being unloaded.
- [x] Report processes being killed.

**Comment by gaborcsardi** [comment]
It does not seem to be possible to work around the lazy-load DB issue. Plus there is also an issue with the registered S3 methods. So it is better to suggest a restart.

**Comment by jimhester** [comment]
You would have to remove or force the promises from lazy loaded data and functions to remove the lazy loaded issues. pkgload already has code to do the former. You would also have to remove all registered S3 methods.

**Comment by gaborcsardi** [comment]
Right. But the same issue exists for the manual pages, and data sets as well, no? Also there is no supported way to de-register S3 methods, and pak does not currently deal with S4 methods, either. 

So it is just simpler to suggest/offer a restart? At least then packages that cannot be reloaded will work as well.

**Comment by gaborcsardi** [comment]
We could still do it for the package namespace, though, it is reasonably fast, even if several packages are unloaded. Then things will at least mostly work if the user chooses not to restart?

Btw. do you think it is worth reporting this? Ideally `unloadNamespace()` would get rid of the lazy load DBs of the package, and it would de-register the S3 methods as well. OTOH it also does not unload the DLL, by choice, so I don't have very high hopes...

**Comment by jimhester** [comment]
I did open a bug years ago about the deregistering the S3 methods (https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16644), was told it was documented behavior and the only way to handle this is to restart R.

**Comment by gaborcsardi** [comment]
Yeah, not worth it then. 

OK, I'll `force()` the package namespace then, and also add a suggestion/offer to restart R.

**Comment by gaborcsardi** [comment]
Btw. another potential issue is `delayedAssign()` and active bindings. These will be probably triggered when we force the symbols in the namespace. They are rare, we use them in a bunch of packages afair?

**Comment by jimhester** [comment]
Yes, @lionel- ran into this recently. I guess you could write code to check the type of promise is a lazy load promise before trying to force it.

**Comment by gaborcsardi** [comment]
There is a `bindingIsActive()` for active bindings, but it seems that there is no R API to check on a promise for `delayedAssign`? So it would have to be compiled code, which also complicates things for pak, slightly.

It also takes a bit of time to force all symbols in all unloaded packages, so I think we can just skip this now. People should reload, for now.

**Comment by jimhester** [comment]
yeah I agree just having people reload is fine, I think the most important thing is to notify them they should reload.

**Comment by gaborcsardi** [comment]
Relevant: https://github.com/r-lib/pkgload/pull/132

**Comment by gaborcsardi** [comment]
RStudio now offers a restart, so all of this is done.
