### ISSUE TITLE
Windows daily build errors

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pak#220]
Because of the missing add-path on GHA? But it does build and publish the package properly, actually, the add-path is not actually needed, I think.

**Comment by jimhester** [comment]
You should be able to fix this by upgrading the version of actions/core used in the pak-builder action.

**Comment by gaborcsardi** [comment]
Thanks! It apparently still builds and deploys fine, but there are a lot weird messages about paths, etc. in the log, probably because of Microsoft R.

**Comment by gaborcsardi** [comment]
Actually, the deployment is skipped because of this error, even though the package is built, so I'll fix this in a minute...

**Comment by gaborcsardi** [comment]
Yeah, updating actions/core fixed it indeed, it was core doing `add-path`, not me. Thanks!
