### ISSUE TITLE
Warning from the package tree

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pak#234]
```
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.

✔ Updated metadata: 4.22 MB in 12 files.

ℹ Updating local metadata database
✔ Updating local metadata database ... done

Warning: Warning: namespace ‘desc’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
local::. 0.1 ✨👷‍♂️ ⬇ (unknown size)
├─r-lib/devtools 2.3.1.9000 ✨👷‍♂️🔧 ⬇ (unknown size)
│ ├─r-lib/usethis 1.9.0.9000 ✨👷‍♂️🔧 ⬇ (unknown size)
```

Probably there is a desc namespace somewhere in the object that is copied from the subprocess.

**Comment by jimhester** [comment]
This is actually quite a bad thing for using pak on the CI, as it is a spurious warning on every build.

**Comment by jimhester** [comment]
It seems to be coming from somewhere in `pkg_deps()`, not `pkg_dep_tree()`, as I still get it from using `pkg_deps()` directly.

**Comment by jimhester** [comment]
Ah I think this is coming from the 'extra' field in the tibble returned from `pkg_deps()`, which contains `desc::description` objects.

**Comment by jimhester** [comment]
Looks like this code as of 10 days ago in R-devel actually has an environment variable (`_R_NO_REPORT_MISSING_NAMESPACES_`) that controls if the warning is emitted (https://github.com/wch/r-source/blob/6ca733fd5098a28e41a3b4c298b9ef6073ae7dfa/src/library/base/R/namespace.R#L38).

So we could set that which would solve this in the future...
