### ISSUE TITLE
Access the installation order

### ISSUE THREAD

**Issue by schloerke** [r-lib/pak#256]
`pak`/`pkgdepends` have been wonderful in resolving all packages before installing them.

Is there a way to access which packages would be installed in what order? Or if it is in a tree-like structure where siblings can be installed in parallel, that would be great!

In particular, looking at `rstudio/shinycoreci` with `dependencies = TRUE`.

The `pkg_deps_tree()` displays the information of which packages are. If the packages are read top down, the second instance of the package name is the _trimmed_ label. I don't believe this represents a valid installation order.

Thank you!

**Comment by gaborcsardi** [comment]
The installation is parallel with multiple processes, and there is no single order. It is essentially any topological order of the dependency graph, with some tweaks, e.g. binary packages can be installed before their dependencies. (But if you install binaries like that, then you need to use the transitive closure of the dependency graph.)

The dependencies are included in the return value of `pkg_deps_tree()` and `pkg_deps()`, in the `deps` column. You need to drop the soft dependencies and the base packages and `R`. E.g. 

```
deps <- pak::pkg_deps("rstudio/shinycoreci")
deps$deps[[2]]
```

```
#> # A tibble: 7 x 5
#>   ref            type     package        op    version
#>   <chr>          <chr>    <chr>          <chr> <chr>
#> 1 R              depends  R              ">="  "3.0"
#> 2 knitr          suggests knitr          ""    ""
#> 3 microbenchmark suggests microbenchmark ""    ""
#> 4 pryr           suggests pryr           ""    ""
#> 5 testthat       suggests testthat       ""    ""
#> 6 ggplot2        suggests ggplot2        ""    ""
#> 7 scales         suggests scales         ""    ""
```
