### ISSUE TITLE
On windows pak_update() needs a R restart afterwards due to corrupted rdb

### ISSUE THREAD

**Issue by cderv** [r-lib/pak#259]
```r
> pak::pak_update()

Updating to version 0.1.2.9001

essai de l'URL 'https://r-lib.github.io/p/pak/dev/bin/windows/contrib/4.0/pak_0.1.2.9001.zip'
Content type 'application/zip' length 14197974 bytes (13.5 MB)
downloaded 13.5 MB

files 'DESCRIPTION', 'Meta/package.rds' have the wrong MD5 checksums

Reloading pak.
Error in fetch(key) : 
  lazy-load database 'C:/Users/chris/Documents/R/win-library/4.0/pak/help/pak.rdb' is corrupt
```

The last message is thrown when I tries to use **pak** after update like `pak::` then tabulation. 

I does not mind restarting. Maybe it could be added as message after "reloading pak" ?

**Comment by gaborcsardi** [comment]
Yeah, if the reloading fails, we could just tell the user that they need to restart the session.

**Comment by cderv** [comment]
Just to add that this also happened to me on Ubuntu (using Windows WSL if that makes a difference) - so it may not be only Windows.

**Comment by gaborcsardi** [comment]
Sure, this happens when you looked at some help files, and the help files in the new version are different.

**Comment by cderv** [comment]
Thanks.
