### ISSUE TITLE
Relax constraint that DESCRIPTION must be for a Package

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pak#271]
The call to `rprojroot::find_package_root_file()` in `pak::local_*()` functions enforces a strict requirement that the `DESCRIPTION` file includes a `Package:` field.

https://github.com/r-lib/pak/blob/49bcef90aa5a48ef0b822d79cae54203acc8673e/R/local.R#L59

`pak::local_install()` is the [current recommended solution](https://github.com/r-lib/remotes/issues/563) for installing packages from a DESCRIPTION that also respects declared package versions. Unfortunately, renv differentiates between `Project:` and `Package:` DESCRIPTION files, which makes it difficult to use `pak::local_*()`.

Relaxing this requirement by using a call like below could make `pak::local_*()` more broadly useful.

```r
rprojroot::find_root_file(path = root, criterion = "description")
```

**Comment by gaborcsardi** [comment]
I would be surprised if just changing that fixed the `local_*` functions for non-package projects. pak/pkgdepends assumes that the local tree is a package at a lot of other places in the code, I suspect.

**Comment by gadenbuie** [comment]
Hmm... but if I change the first line of the DESCRIPTION file to read `Package: ...` it works as expected. There are definitely other places where that criterion is applied, but if the DESCRIPTION file is found and correctly formatted it seems likely that `local_*` would work.

**Comment by gaborcsardi** [comment]
Unfortunately it is more difficult than that. E.g. `desc::desc()` will fail as well, probably for the same reason, and pak/pkgdepends uses desc internally. The dependency solver works with package names as well.

But if you want to experiment with this, feel free to update pkgdepends, and then we'll have a better idea what needs to be updated.

**Comment by jimhester** [comment]
All of the tooling we built expects DESCRIPTION files to have `Package:` entries, it is basically the old field that is guaranteed to exist for an R package DESCRIPTION file.

I would suggest renv propose a different solution if they want to use these packages to install dependencies.

**Comment by gadenbuie** [comment]
Sorry all, I was wrong about renv's expected DESCRIPTION format and use of the `Package:` field. renv uses `Type: Project` and `Type: Package` to differentiate. Please ignore all of the above!
