### ISSUE TITLE
Do not let pkg_deps() fail even when some dependencies are unavailable

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/pak#290]
Since it might be the case for older versions of R. We are trying to switch GHA CI to use pak but because of this reason the CI won't run.

https://github.com/tidyverse/ggplot2/pull/4425#issuecomment-821177588

**Comment by gaborcsardi** [comment]
Are you sure you want to build the pkgdown site without those suggested packages? Why not just fix their installation?

**Comment by yutannihilation** [comment]
No, I meant `check-pak` action, not `pkgdown-pak`.

**Comment by yutannihilation** [comment]
> Why not just fix their installation?

What I meant by "unavailable" is not that the CI fails to install the package, but some packages that specifies "R >= x.x" as "Depends" doesn't exist on the package index on the runner of older version of R, which is not what I can fix.

Currently, `check-pak` uses `pkg_deps()` and it fails on ggplot2 repo because some dependencies are literally unavailable.

https://github.com/r-lib/actions/blob/0d6c4b3efe82090bc03e99c585d9e89003117931/examples/check-pak.yaml#L57

If it's r-lib/action that I should file this issue, please let me know. I still don't see how this should be fixed.

**Comment by gaborcsardi** [comment]
Yeah, this will definitely need some support from pak, and I have some ideas on how to express this in `DESCRIPTION` or in an argument.

Unfortunately I don't have a simple workaround for now. You could temporarily remove the problematic dependencies when using pak, on the older R versions, with `desc::desc_dep_dep()` and `desc::desc_set_dep()`. Somewhat cumbersome, but it could work.

**Comment by yutannihilation** [comment]
Thanks, I'll try tweaking the CI scripts for now.

**Comment by gaborcsardi** [comment]
This is now possible with `?ignore` and `?ignore-before-r`: see some GHA oriented docs here-ish: https://github.com/r-lib/actions/tree/v2/setup-r-dependencies#ignoring-optional-dependencies-that-need-a-newer-r-version

**Comment by yutannihilation** [comment]
Wow, great! Thanks!
