### ISSUE TITLE
How to customize private directory path

### ISSUE THREAD

**Issue by liutiming** [r-lib/pak#291]
Thanks for this awesome package! I am working on a cluster with very little space in `~`. Can I customize where to install the packages?

**Comment by gaborcsardi** [comment]
Can you use the bundle we provide?

```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
```

This is already as small as possible, e.g. documentation, vignettes, etc. are removed from it. For R 4.0 it is 18MB installed and I can still look into making it smaller.

**Comment by liutiming** [comment]
thanks! I was thinking if we can determine where `pak` will install packages: now it will create the private package library in my home directory and I cannot find an option to specify an alternative in `pak_setup`

**Comment by gaborcsardi** [comment]
If you install it the way I told you, it will not create a private library at all. `pak_setup()` does nothing in the dev version.

**Comment by liutiming** [comment]
Yup thank you!
