### ISSUE TITLE
Expose RSPM API function calls

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/pak#299]
The system deps functionality relies on the PPM REST API. It would be beneficial if these endpoints were available for more flexible calls to the api. I [began working](https://github.com/josiahparry/rspmapi) on this, however the pak implementation seems a bit more robust. 

https://github.com/r-lib/pak/blob/2c4cc467fbf8c38058529b817b73e98c4fb08918/R/system-requirements.R#L71

**Comment by gaborcsardi** [comment]
I am sorry, pak will not do that, at least not in the near future. Our sysreqs implementation is still changing and I don't want to make it public.
