### ISSUE TITLE
lib_ functions

### ISSUE THREAD

**Issue by jimhester** [r-lib/pak#3]
- [x] lib_create()

- [ ] lib_status() 
- [x] lib_activate()  # wrappers around .libPaths()
- [x] lib_deactivate()

- [x] lib_temporary() # create an active session specific temporary library

- [ ] lib_upgrade() # should go into different dir?
- [ ] lib_check() # ensure in a consistent/self-contained state (i.e. all deps installed, all for same platform, r version etc)
(When operating in project-library mode, any install should warn if you make the library inconsistent)

- [ ] lib_record() # record all versions of packages in a suitable way to transmit to someone else. Should also record R version.
- [ ] lib_replay() # install all packages from recording

**Comment by jimhester** [comment]
`lib_system_check()` to check system dependencies / query system dependencies for packages.

**Comment by gaborcsardi** [comment]
> `lib_system_check()` to check system dependencies / query system dependencies for packages.

Why is this a `lib_` function. System dependencies belong to packages, no?

**Comment by jimhester** [comment]
It would check the system dependencies for all packages in a library
