### ISSUE TITLE
Identify installed packages by source

### ISSUE THREAD

**Issue by noamross** [r-lib/pak#30]
It would be useful to be able to identify the install source of installed packages (CRAN, BioC, GitHub repo,...).  My current use-case is identifying which packages are installed from GitHub ahead of CRAN, so I can revert those packages to CRAN versions for a stable environment for teaching/reproducibility.

**Comment by jimhester** [comment]
For future reference maybe something like

```r
pkg_ls() %>% filter(source = “github”)
```

**Comment by gaborcsardi** [comment]
We'll have `pkgman::pkg_status()` for a whole library, and that will contain a column for the source.

**Comment by jimhester** [comment]
`pak::lib_status()$remotetype has this information.
