### ISSUE TITLE
Changing the BioC version

### ISSUE THREAD

**Issue by ChristopherEeles** [r-lib/pak#309]
Hello `pak` devs,

Really like the new package. I develop primarily for Bioconductor though, and thus I need to use the development version. Unfortunately for the Spring release BioC release and devel both use the same R version.

Is there a way I can change the default BioC source from 3.13 to 3.14? I imagine this will be a common problem for people working in bioinformatics.

Best,
Christopher Eeles
Software Developer @ BHKLab
Princess Margaret Cancer Centre

**Comment by gaborcsardi** [comment]
Actually, 3.14 seems to be the default for me, maybe Bioconductor has changed the default:

```r
❯ R-4.2 -q -e 'getRversion()'
> getRversion()
[1] ‘4.2.0’
```

```r
❯ R-4.2 -q -e 'pak::repo_get()'
> pak::repo_get()
# A tibble: 5 x 5
  name        url                                   type  r_version bioc_version
  <chr>       <chr>                                 <chr> <chr>     <chr>
1 CRAN        https://cloud.r-project.org           cran  *         NA
2 BioCsoft    https://bioconductor.org/packages/3.… bioc  4.2.0     3.14
3 BioCann     https://bioconductor.org/packages/3.… bioc  4.2.0     3.14
4 BioCexp     https://bioconductor.org/packages/3.… bioc  4.2.0     3.14
5 BioCworkfl… https://bioconductor.org/packages/3.… bioc  4.2.0     3.14
```

You can change the default with the `R_BIOC_VERSION` env var, see https://github.com/r-lib/pkgcache#bioconductor-support

```r
❯ R_BIOC_VERSION=3.13 R-4.2 -q -e 'pak::repo_get()'
> pak::repo_get()
# A tibble: 5 x 5
  name        url                                   type  r_version bioc_version
  <chr>       <chr>                                 <chr> <chr>     <chr>
1 CRAN        https://cloud.r-project.org           cran  *         NA
2 BioCsoft    https://bioconductor.org/packages/3.… bioc  4.2.0     3.13
3 BioCann     https://bioconductor.org/packages/3.… bioc  4.2.0     3.13
4 BioCexp     https://bioconductor.org/packages/3.… bioc  4.2.0     3.13
5 BioCworkfl… https://bioconductor.org/packages/3.… bioc  4.2.0     3.13
```

**Comment by ChristopherEeles** [comment]
Hi @gaborcsardi,

Bioconductor 3.14 packages are not designed for R 4.2. This is due to the biannual release cycle for Bioconductor versions. In Spring, both Bioconductor 3.13 and 3.14 are intended for the current R release. In the Fall, the release and development version (e.g., 3.15, 3.16) will be designed for R 4.1 and 4.2, respectively.

This shouldn't affect people who use Bioconductor packages, but it does affect developers. Since I want my packages to pass the checks in the same R version as the automated build system, I need R 4.1 with BioC 3.14.

I can do that with the information you provided though, so thank you 😄.

Best,
Christopher Eeles
Software Developer @ BHKLab
Princess Margaret Cancer Centre
