### ISSUE TITLE
Error: callr subprocess failed: Invalid parent_resolve callback

### ISSUE THREAD

**Issue by OlivierBinette** [r-lib/pak#312]
I'm running R version 3.6.3 on platform x86_64-pc-linux-gnu.

First time trying to install and use pak, I got the following error:
```r
install.packages("pak")
pak::pak_setup()
pak::pkg_install("assert")
# Error: callr subprocess failed: Invalid parent_resolve callback
```

Same error when trying `pak::pkg_install("devtools")` or any other package. Same problem as well on my macOS (10.14.6) laptop running R version 4.1.0

**Comment by OlivierBinette** [comment]
Just tried installing the development version of `pak` and I don't get any error with it.

**Comment by JamesHWade** [comment]
I am getting that same error, but I have installed the dev version.

**Comment by gaborcsardi** [comment]
What is the output of `pak::pak_sitrep()`?

**Comment by JamesHWade** [comment]
I must have failed to install dev, because it's working now. I also installed a bunch of system libraries (fresh Ubuntu install), so I'm not sure if that made a difference. Sorry for the trouble.

**Comment by gaborcsardi** [comment]
For the record, no system libraries are needed, and the best way to install the dev version is as at https://github.com/r-lib/pak#installation
