### ISSUE TITLE
tibble not available for pak?

### ISSUE THREAD

**Issue by MansMeg** [r-lib/pak#314]
Hi!

I get a strange error message that just showed up. It seem strange that ```tibble``` would not be available? 

```
! Optional package `tibble` is not available for pak.
  Use `pak::pak_install_extra()` to install optional packages.
  Use `options(pak.no_extra_messages = TRUE)` to suppress this message.
```

The full github actions run can be found here:
https://github.com/stan-dev/posteriordb-r/runs/3511995070?check_suite_focus=true

**Comment by gaborcsardi** [comment]
It is not an error, it is a message, and you can ignore it or suppress it like the message says.

**Comment by MansMeg** [comment]
Unfortunately it breaks my build on Github actions. I guess this will break a lot of builds?

**Comment by MansMeg** [comment]
Sorry. The formal error message comes right after:

Error: Error: <callr_remote_error: missing value where TRUE/FALSE needed>

**Comment by gaborcsardi** [comment]
It will not break any builds, because it is not an error. It also seems that this was a caused by a typo in your `DESCRIPTION` file.

**Comment by MansMeg** [comment]
Yes, sorry for the confusion.
