### ISSUE TITLE
Include dependency resolution for GHA

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#319]
Need single function that encapsulates current approach: https://github.com/r-lib/actions/blob/master/setup-r-dependencies/action.yaml#L43-L57

* Read from selected `Config/needs` field
* Take vector of lower priority extra packages (https://github.com/r-lib/actions/issues/386)
* Don't include `local::.` in packages to install

**Comment by gaborcsardi** [comment]
These are all fixed now in various places:
- pak
- https://github.com/r-lib/pkgdepends
- https://github.com/r-lib/actions/tree/pak2
