### ISSUE TITLE
Should remoteSha be set for installation of CRAN packages?

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/pak#329]
I noticed that for CRAN packages `remoteSha` takes the package version number.

A downstream effect of this is that CRAN packages get written to `{renv}` lockfiles like this:

```
    "DBI": {
      "Package": "DBI",
      "Version": "1.1.1",
      "Source": "CRAN",
      "Repository": "CRAN",
      "RemoteType": "standard",
      "RemotePkgRef": "DBI",
      "RemoteRef": "DBI",
      "RemoteRepos": "https://cran.rstudio.com",
      "RemotePkgPlatform": "windows",
      "RemoteSha": "1.1.1",
      "Hash": "030aaec5bc6553f35347cbb1e70b1a17"
    },
```

I had some logic to check if lockfiles and libraries are in sync. It threw a warning if version numbers are the same but SHAs are different, including if one SHA was NA and one was set. This threw warnings when a non-pak user checked a lockfile written by a pak user.

I can fix the logic etc. But I wonder if the `remoteSha` field should be used for version numbers at all since these represent different concepts?

**Comment by gaborcsardi** [comment]
> But I wonder if the remoteSha field should be used for version numbers at all since these represent different concepts?

devtools/remotes uses this convention:
https://github.com/r-lib/remotes/blob/eb15a1eb21cca47ce5601747fd4e033d8606a648/R/install-cran.R#L57
So it would be hard to remove, and the benefits would not be great.
