### ISSUE TITLE
README: Update refs to `pak::pak_setup()`

### ISSUE THREAD

**Issue by ddsjoberg** [r-lib/pak#338]
Hey hey, I was poking around to review the updates in v0.2.0. I noticed the README includes the sentence below

> (After installation, you might also want to run `pak::pak_setup()`; it’ll be run automatically when needed but you might want to do it now to save some time later.)

When I went to the function's help file, I saw that it is now deprecated. Perhaps, the reference to this function should be removed from the landing page.

Thanks :)

**Comment by dpprdan** [comment]
I think this has been fixed in the meantime.
