### ISSUE TITLE
lockfile_install() error when "lockfile" argument is not pointing to a lockfile in working directory

### ISSUE THREAD

**Issue by merlinoa** [r-lib/pak#340]
Hi,

When I try to install a lockfile that is not located in the working directory e.g.

```
lockfile_install(lockfile = "my_dir/pkg.lock")
```

I get the following error:

```
Error: cannot open the connection
Type .Last.error.trace to see where the error occurred 
```

The installation works fine when the "pkg.lock" file is in my working directory.

I have tried with the new CRAN release and the current dev version on GitHub, but I get the same error with both of them.

Is this expected behavior?  Sorry if I am missing something obvious.

**Comment by gaborcsardi** [comment]
So what happens if you type in `.Last.error.trace` and `.Last.error` right after the error?

**Comment by merlinoa** [comment]
Well I just tried to recreate the error and it is working now...

This is what I was getting before when running `.Last.error.trace`

```
Stack trace:

 12. (function (...)  ...
 13. base:::withCallingHandlers(cli_message = function(msg) { ...
 14. get("lockfile_install_internal", asNamespace("pak"))(...)
 15. pkgdepends::new_pkg_installation_plan(lockfile, config = config)
 16. pkg_installation_plan$new(lockfile, config = config, ...)
 17. pkgdepends:::initialize(...)
 18. pkg_plan$new(lockfile = lockfile, config = config, library = config$library ...
 19. pkgdepends:::initialize(...)
 20. pkgdepends:::pkgplan_init(self, private, refs, config, library,  ...
 21. pkgdepends:::pkgplan_init_lockfile(self, private, lockfile, config,  ...
 22. jsonlite:::fromJSON(readLines(lockfile), simplifyVector = FALSE)
 23. base:::readLines(lockfile)
 24. base:::file(con, "r")
 25. base:::.handleSimpleError(function (e)  ...
 26. h(simpleError(msg, call))
 27. base:::stop(e)
 28. (function (e)  ...

 x cannot open the connection 
```

Since I could not reproduce the error I could not run`.Last.error`.

If you're interested, the lock file I was using is attached. I appended a ".txt" onto the file name so that GitHub would allow me to attach it.

Closing this out since it is working.  I'll reopen if I hit it again.  Thanks for your super quick response and thanks for this package!

[pkg.lock.txt](https://github.com/r-lib/pak/files/7672598/pkg.lock.txt)
