### ISSUE TITLE
Feature Request: pak equivalent of `update.packages`?

### ISSUE THREAD

**Issue by ChristopherEeles** [r-lib/pak#341]
Maybe this feature already exists, but I couldn't find any reference to it in the read me?

Expected behavior would be equivalent to `update.packages()`, but using the `pak` package installation infrastructure.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by dpprdan** [comment]
See #289

**Comment by gaborcsardi** [comment]
Closing, because it is a duplicate.
