### ISSUE TITLE
Failed installation of chrome system requirement

### ISSUE THREAD

**Issue by cderv** [r-lib/pak#347]
This issue occured in a recent workflow (https://github.com/rstudio/blogdown/runs/4580524115?check_suite_focus=true#step:5:2942)

````
ℹ Executing `sudo [ -e /tmp/google-chrome.deb ] && rm /tmp/google-chrome.deb`
  
  Error: Error: <callr_remote_error: System command 'sh' failed, exit status: 1, stdout + stderr empty>
   in process 8955 
  -->
  System command 'sh' failed, exit status: 1, stdout + stderr empty
````

I believe this comes from **webshot2** which uses **chromote**. However, on GHA `google-chrome` should already be available.

I don't really know how all this happens but the rules followed must be this one: 
https://github.com/rstudio/r-system-requirements/blob/master/rules/chrome.json

**Comment by gaborcsardi** [comment]
Yes, we cannot just prepend `sudo` to the command coming from the system requirements DB, apparently. Maybe we should run the shell in sudo instead:
```
❯ sudo false || id -u
501

~/works/pkgbuild main
❯ sudo sh -c 'false || id -u'
0
```

**Comment by gaborcsardi** [comment]
This should be fixed now.
