### ISSUE TITLE
Integration with bspm

### ISSUE THREAD

**Issue by Robinlovelace** [r-lib/pak#349]
I have just tested [`bspm`](https://github.com/Enchufa2/bspm) and am seriously impressed: after installing it and running the following command on my Ubuntu laptop

```bash
echo "bspm::enable()" | sudo tee -a /etc/R/Rprofile.site
```

`install.packages()` installs binary versions of packages. And it seems to work on most popular open source operating systems.

Having seen #299 I'm wondering if support for `bspm` could be a useful feature.

**Comment by gaborcsardi** [comment]
bspm seems to be a different way of installing R packages, and it does not need pak, and pak does not need bspm. So we are not planning on working on this for now.
