### ISSUE TITLE
"Cannot load glue from the private library" error after installing binary from CRAN

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pak#352]
For example:

```
> utils::install.packages("pak", type = "binary")
Installing package into ‘C:/Users/kevin/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/pak_0.2.1.zip'
Content type 'application/zip' length 307511 bytes (300 KB)
downloaded 300 KB

package ‘pak’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kevin\AppData\Local\Temp\Rtmpm2SWu3\downloaded_packages
> library(pak)
Warning message:
package ‘pak’ was built under R version 4.1.2 
> pkg_install("rlang")
Error in load_private_package("glue") : 
  Cannot load glue from the private library
```

It looks like the `pak` binaries on CRAN were built without the embedded private library.

The binaries from the `pak/devel` repository appear to be fine:

```
> install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
Installing package into ‘C:/Users/kevin/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://r-lib.github.io/p/pak/devel/bin/windows/contrib/4.1/pak_0.2.0.9000.zip'
Content type 'application/zip' length 14432952 bytes (13.8 MB)
downloaded 13.8 MB

package ‘pak’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kevin\AppData\Local\Temp\RtmpcvoDBZ\downloaded_packages
```

**Comment by gaborcsardi** [comment]
This is still #339. You need to install from source on Windows, until this is fixed.

**Comment by kevinushey** [comment]
Thanks -- sorry I missed that.

**Comment by gaborcsardi** [comment]
No worries. The next CRAN release will get this right, I am (well, almost) sure.

**Comment by ScientificProgrammer** [comment]
Hello `pak` Devs:

I found this discussion thread via Google. I attempted to install `rsquaredacademy/pkginfo` using `pak::pkg_install()` and received "*private library*" error (see below).

    > pak::pkg_install("rsquaredacademy/pkginfo")
    Error in load_private_package("glue") : 
      Cannot load glue from the private library

---

Although, I wasn't able to use `pak` to install my desired package, I did get it installed via `remotes::install_github()`, as shown here.

    > remotes::install_github("rsquaredacademy/pkginfo", force = TRUE, build_vignettes = TRUE)
    Using github PAT from envvar GITHUB_PAT
    Downloading GitHub repo rsquaredacademy/pkginfo@HEAD
    √  checking for file 'C:\Windows\Temp\RtmpuAZ9rq\remotes26d433954339\rsquaredacademy-pkginfo-5a5004c/DESCRIPTION' ... 
    -  preparing 'pkginfo': (989ms)
    √  checking DESCRIPTION meta-information ... 
    -  checking for LF line-endings in source and make files and shell scripts
    -  checking for empty or unneeded directories
       Omitted 'LazyData' from DESCRIPTION
    -  building 'pkginfo_0.1.0.tar.gz'
       
    * installing *source* package 'pkginfo' ...
    ** using staged installation
    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
      converting help for package 'pkginfo'
        finding HTML links ... done
        CranPackage                             html  
        GitHubRepo                              html  
        build_info                              html  
        get_pkg_cran_check_results              html  
        get_pkg_details                         html  
        get_pkg_downloads                       html  
        get_so_questions                        html  
        github_info                             html  
        package_info                            html  
        pkginfo                                 html  
        pkginfo_dashboard                       html  
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    *** arch - i386
    *** arch - x64
    ** testing if installed package can be loaded from final location
    *** arch - i386
    *** arch - x64
    ** testing if installed package keeps a record of temporary installation path
    * DONE (pkginfo)

---

In case this information helps you, I'm running `R` under `RStudio` on `Windows`. My `RStudio` version information and `R` `sessionInfo()` output are listed below. Please let me know if I can help some other way.


### RStudio version information

    RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Windows
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36


### Output of `sessionInfo()`

    > sessionInfo()
    R version 4.1.1 (2021-08-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 22000)

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
     [1] pak_0.2.0.9000    ps_1.6.0          prettyunits_1.1.1 crayon_1.4.2      withr_2.4.3      
     [6] rprojroot_2.0.2   R6_2.5.1          cli_3.1.0         curl_4.3.2        remotes_2.4.1    
    [11] rstudioapi_0.13   callr_3.7.0       tools_4.1.1       compiler_4.1.1    processx_3.5.2   
    [16] pkgbuild_1.2.0

**Comment by kevinushey** [comment]
@ScientificProgrammer: the solution for now is to reinstall `pak` from sources, e.g.

```
install.packages("pak", type = "source")
```

Or alternatively, you can install a binary from the latest development version here:

```
install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
```

**Comment by c1au6i0** [comment]
I am still having the same error in my workflow in Windows even when installing `pak` from sources or from the `devel` repo
```
Run install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
# Bootstrapping renv 0.14.0 --------------------------------------------------
* Downloading renv 0.14.0 ... OK (downloaded binary)
* Installing renv 0.14.0 ... Done!
* Successfully installed and loaded renv 0.14.0.
Installing package into 'D:/a/mypackage/mypackage/renv/library/R-4.1/x86_64-w64-mingw32'
(as 'lib' is unspecified)
trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/4.1/pak_0.2.1.zip'
Content type 'application/zip' length 307511 bytes (300 KB)
==================================================
downloaded 300 KB

package 'pak' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\runneradmin\AppData\Local\Temp\RtmpkpN9Oz\downloaded_packages
Error in load_private_package("glue") : 
  Cannot load glue from the private library
Calls: saveRDS ... new_remote_session -> load_private_packages -> load_private_package
Execution halted
```

**Comment by gaborcsardi** [comment]
That does not look like `install.packages()` but renv and it does not use the repo provided, but `http://lib.stat.cmu.edu`.

**Comment by c1au6i0** [comment]
Not sure. In that step I just run 
```
install.packages("pak", type = "source")
saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
```
It fails on `windows-latest` but run fine in `Ubuntu` or `MacOs`.  I try to do some more digging...

**Comment by gaborcsardi** [comment]
There is not much digging to be done, the Windows pak binaries are broken on CRAN. 

```
trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/4.1/pak_0.2.1.zip'
```
clearly means that you did not install it from `repos = "https://r-lib.github.io/p/pak/devel/"`.

**Comment by c1au6i0** [comment]
I see thanks

**Comment by kevinushey** [comment]
@c1au6i0, sorry, you're running into a bug in renv 0.14.0 where the `renv` shim for `install.packages()` was not forwarding arguments properly to `utils::install.packages()`. This should be fixed in the recently released renv 0.15.0.

**Comment by c1au6i0** [comment]
@kevinushey no problem, thank you Kevin!

**Comment by ScientificProgrammer** [comment]
@gaborcsardi 
> There is not much digging to be done, the Windows pak binaries are broken on CRAN.
> ```
> trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/4.1/pak_0.2.1.zip'
> ``` 
> clearly means that you did not install it from `repos = "https://r-lib.github.io/p/pak/devel/"`.

I'm hoping to understand this issue better. If I were to build R from source on my Windows computer—instead of installing the CRAN binaries—do you know if this same bug would still be present?

For example,

1. is someone hard-coding the CMU CRAN mirrors into the Windows binaries they built and distribute for CRAN, or

1. is the problem more fundamental, in that the R source code logic is just wrong, and the ```install.packages()``` function simply ignores the ```repo=``` option and will always use the CMU  CRAN mirror regardless?

I realize that I could search the source code myself to answer this question, but that process would take me a while to complete, since I haven't looked at the R source code in a long time. I'm asking on the chance that you or one of the team here might just know the answer.

Thanks!

**Comment by gaborcsardi** [comment]
> I'm hoping to understand this issue better. If I were to build R from source on my Windows computer—instead of installing the CRAN binaries—do you know if this same bug would still be present?

It does not matter how you build R, what matters is whether you use the binary _packages_ from CRAN or not. 

> is someone hard-coding the CMU CRAN mirrors into the Windows binaries they built and distribute for CRAN, or

I don't think so.

> is the problem more fundamental, in that the R source code logic is just wrong, and the install.packages() function simply ignores the repo= option and will always use the CMU CRAN mirror regardless?

As Kevin said above, there was a bug in renv, and it ignored the specified `repos` option so it always used the user's default which I assume was the CMU mirror for the user above.

**Comment by gaborcsardi** [comment]
I don't think there is much to learn here for most people, there are two bugs.

One pak bug that makes the pak binaries on CRAN broken. 

Plus one (already fixed) renv bug, that ignores the `repos` option of renv's `install.packages()` function.

**Comment by ScientificProgrammer** [comment]
@gaborcsardi 

> I don't think there is much to learn here for most people, there are two bugs, neither which particularly interesting. :)
> 
> One pak bug that makes the pak Windows binaries on CRAN broken.
> 
> Plus one (already fixed) renv bug, that ignores the `repos` option of renv's `install.packages()` function.

Thank you for the very helpful explanations. You read my mind!
