### ISSUE TITLE
`pak::pkg_system_requirements(pkgs, execute = TRUE)` will throw error

### ISSUE THREAD

**Issue by psychelzh** [r-lib/pak#353]
For example:

![image](https://user-images.githubusercontent.com/13306020/148003404-74ee907d-caff-463e-a443-7763dde0620f.png)

Error trace:

![image](https://user-images.githubusercontent.com/13306020/148003444-c0281158-ae32-4338-889c-914c5d784b3c.png)

**Comment by psychelzh** [comment]
This will work for older versions.

**Comment by gaborcsardi** [comment]
I don't see how this worked in previous versions, because `sudo` is called in a background process, without a terminal, so this only works if you have a password-less `sudo` setup.

**Comment by psychelzh** [comment]
Thank you! I have found a way to do it in my server side.
