### ISSUE TITLE
How to invoke pkg_install to reference MRAN timemachine

### ISSUE THREAD

**Issue by dmonder** [r-lib/pak#357]
The documentation for installing a package from MRAN is not clear. I think I need to install the repo first by invoking `pak::repo_add(MRAN_JAN21 = "MRAN@2021-01-01")` to install from 1/1/21. I would have thought I needed to then invoke `pkg_install("MRAN_JAN21 ::tidyverse")` to install the version of tidyverse from 1/1/21. However, this gives the following error:
```
Error: Unknown remote type(s): `MRAN_JAN21`
```

I think the documentation should be enhanced to clarify how to do an install from MRAN (or maybe there is an actual error in the code and that needs to be fixed 😉).

**Comment by gaborcsardi** [comment]
If you just want to set the CRAN repo, you can set `options("repos")` as usual. You can also do it with `repo_add()` if you like, the end result will be the same:
```r
❯ pak::repo_add(CRAN = "MRAN@2021-01-01")
❯ getOption("repos")
                                            CRAN
"https://cran.microsoft.com/snapshot/2021-01-01"
```
and then you can use `pak::pkg_install()` as usual.

**Comment by dmonder** [comment]
Ahhh, that makes sense. Thank you. Works perfectly.
