### ISSUE TITLE
Add version control a-la groundhog

### ISSUE THREAD

**Issue by urisohn** [r-lib/pak#359]
Following up on email exchange with Gabor.

I wanted to propose incorporating into 'pak' the type of version control (as an option perhaps) used by the CRAN package _groundhog_.

In groundhog you call groundhog.library(pkg,date), instead of library(pkg), and you install if needed, and then make locally available, the version of the package an all dependencies as available on that date on CRAN (the latest releast available in any format that day). 

So you don't explicitly install packages, they are installed if necessary. 

When installing, groundhog looks for binaries on CRAN, then MRAN, and then source if not available.  But it looks for the binary of the exact version needed only, it does not settle for another version in binary.

Same for all dependencies. 

When a package version is installed, it does not replace an existing version, it is installed on its won version-designated folder, so when using a newever version of a package for a script, you don't risk making previous scripts no longer work, older scripts will continue loading the same older versions.

If within the same R session, the same package is called with different dates that imply different versions, groundhog stops the loading and asks users to eitehr restart the session or choose a compatible date.

This is obviously somewhat similar to renv in goals, but attained in a different way that does not seem would be too difficult to incorporate as optional functionality into 'pak'

It has a few advantages over 'renv', for those uses, including that version control is human-readable instead of hidden as supporting files, and thus also version control does not require additional files. It does not require that users implement their scripts within a version control environment, e.g., github project, the way 'renv' nearly requires.  As the maintainer of renv stated to me: '_The primary mode for collaboration with renv is "use a project directory, and find a way to share that directory with others.'_
That is a great solution for many use cases, but it is not a good solution for many others (e.g., sharing R scripts that support a published research paper).

In terms of the current ability by 'pak' and a few other packages of installing a specific version of the package, this is in my mind inferior to groundhog for a few reasons, including that (1) the version of a package served by MRAN depends on the operating system and R version being used to do the install, so version control is imperfect (the same script does different things on different computers) (2) the new install replaces existing packages (it does not in groundhog), (3) the package needs to be re-installed every time it is used in a different script to ensure the correct version is being used (groundhog stores alternative versions locally side by side).

Groundhog works well with CRAN, and may include github and gitlab packages soon, but I personally would prefer if another mainstream package incorporated the approach and made groundhog redundant.

This is a pitch. If there is any interest, i am happy to discuss further.

**Comment by gaborcsardi** [comment]
Unfortunately this is not so simple, because of the dependencies. If
you install a package, what data should their dependencies come from?
The same date? What if for another package you specify another date
and this package has the same dependency. That's a conflict.

FWIW you can use renv with scripts, one of its main goals was to work
with scripts.

You can also install packages from a specific date, using the MRAN
service or RSPM. pak has built in support for this:

```r
❯ pak::repo_add(CRAN = "MRAN@2020-01-21")
❯ pak::repo_get()
# A tibble: 5 × 5
  name          url                                 type  r_version bioc_version
  <chr>         <chr>                               <chr> <chr>     <chr>
1 CRAN          https://cran.microsoft.com/snapsho… cran  *         NA
2 BioCsoft      https://bioconductor.org/packages/… bioc  4.1.2     3.14
3 BioCann       https://bioconductor.org/packages/… bioc  4.1.2     3.14
4 BioCexp       https://bioconductor.org/packages/… bioc  4.1.2     3.14
5 BioCworkflows https://bioconductor.org/packages/… bioc  4.1.2     3.14
```

```r
❯ getOption("repos")
                                            CRAN
"https://cran.microsoft.com/snapshot/2020-01-21"
```

```r
❯ pak::pkg_install("cli")
✔ Updated metadata database: 3.64 MB in 10 files.
ℹ R 4.1 aarch64-apple-darwin20 packages are missing from CRAN and Bioconductor
✔ Updating metadata database ... done

→ Will update 1 package.
→ The package (482.06 kB) is cached.
+ cli 3.1.0.9000 → 2.0.1 👷🏻‍♀️

? Do you want to continue (Y/n) n
Error: Aborted.
```

**Comment by urisohn** [comment]
1) For dependencies, yes, same date, everything is loaded for the same date avoiding possibility that a package change breaks a reverse dependency. Users are warned if there is a conflict, but groundhog.library() loads all dependencies for that date.
2) MRAN date does not guarantee same version, user still can be prompted for binary vs source (with diff versions) and the binary offered may differ base on R version and operating system, and that applies to every dependency as well of course.
3) Also, version control via MRAN date means every time you want to use a given version of a package you have to re-install it, and that a script which does not explictly install it has no version control.

But ok, just wanted to pitch the idea. Thanks for the reply.

**Comment by urisohn** [comment]
Sorry, not enough of a developer to fully understand what is meant by manifest file. 
But let me try two things

1) Here is an explanation of how the back end of groundhog works
[(https://groundhogr.com/back-end/)]


2) An example. Let's load 'metafor' as available on 2021-12-01
```
install.packages('groundhog')
library('groundhog')
groundhog.library('metafor','2021-12-01')
```
Groundhod finds the version of metafor on that date,  it is version 3.0-2 
(you can see version history with groundhog::toc('metafor')
It also finds all the dependencies for that version and the current version for those dependencies on that date.
This is done relying on a daily updated dataframe that contains all package versions available on cran ever.
(https://groundhogr.com/cran.toc.rds) 

It then checks wchich of those depedencies are currently available as binary from CRAN and gets them, then checks which are available from MRAN as binary, and does the rest from source.
The availability on MRAN is computed using release dates of R and packages.

Sorry if that's not what you meant.

**Comment by gaborcsardi** [comment]
Thanks! So where does the code in your example go? In the script?

**Comment by urisohn** [comment]
yeah, that's just the start of the script, the way one normally would use library() to load all pkgs

**Comment by gaborcsardi** [comment]
There are several issues with this, one is that if you do this to a package that was already loaded in a previous step, then you end up with different package versions in the R session and on the disk. Which is undefined behavior in general. On Wiindows, if the package has compiled code, then R locks the DLL file of the package, and the second installation will simply fail.

In general, it is best to keep script execution and package installation separate. E.g. if you deploy a script that has an renv lock file (the manifest), you can install the packages using the lock file at the time of the deployment, and then run the script happily with the deployed packages.

**Comment by urisohn** [comment]
Yes, that's super important. And not just for dll conflicts but for version control. The goal is 100% reliability of exactly which package is being executed. Groundhog checks for these clashes. For example, if you try this

```
library('groundhog')
groundhog.library('broom','2021-12-10')
#some code
groundhog.library('glue','2022-01-01')
```
Groundhog will check that glue is already loaded with a different version and produce this output (without attempting to load it)

_groundhog says:
1 of the 1 packages needed for 'glue_1.6.0' have a version conflict with
a package already in your current R session.

   Current: glue_1.5.1
   Needed:  glue_1.6.0

To solve this: restart the R session. Note: you will need to do 'library(groundhog)' again.

In R Studio press: CTRL/CMD-SHIFT-F10
The package 'glue_1.6.0' was *NOT* attached_

**Comment by gaborcsardi** [comment]
> To solve this: restart the R session.

But if I do that, I'll run into the same issue, unless I somehow harmonize the package versions.

In any case, thanks for the explanations, but I think we're not going to pursue this in pak. We try to keep the package installation and the actual usage separate.
