### ISSUE TITLE
Question: does pak support install packages hosted in github private repo?

### ISSUE THREAD

**Issue by jonekeat** [r-lib/pak#377]
I noticed `pak::pkg_install()` does not has `auth_token` parameter like `remotes::install_github()`, and **https://github.com/r-lib/actions/blob/v2/setup-r-dependencies/action.yaml** was using `pak` to install package dependencies, and I cannot run CI for my package which depends on some private repo 

may I know is there anyway to workaround or is there plan to support this feature?

**Comment by gaborcsardi** [comment]
Yes, it uses the git credential store, so on your machine, you can use `gitcreds::gitcreds_set()` to add your token. (If you haven't added it with command line git or some other tool.)

It also uses the `GITHUB_PAT` environment variable, that is probably easier to use than setting up the credential store on the CI.

**Comment by jonekeat** [comment]
Thanks for the promptly reply Gabor, I just realized the default `GITHUB_PAT` token provided by Github Action does not give me permission to install (or read) other private repositories, so I created another PAT which has these permission and store it as Github secrets as stated in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions

So it is not `pak` problem, `pak` works great with `GITHUB_PAT` env variable! I am closing this issue, thanks again for the help
