### ISSUE TITLE
FR: option to install a specific version

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/pak#394]
Hi,

`pkg_install()` could have another argument named `version` which would install the specific version from the archives, similarly to what `devtools::install_version` would do (but with the nice `pak` spices).

This would be really nice for the default use-case, i.e. install from CRAN, which is 99% of my own use. I don't know how this would articulate with other syntaxes though.

cc https://github.com/r-lib/pak/issues/360

**Comment by jrosell** [comment]
See #122

At the moment, you can use something like this:

```
pak::pkg_install(c('cran/cli@3.4.0'))
```

**Comment by gaborcsardi** [comment]
See the comment above for the solution.
