### ISSUE TITLE
pak GitHub site unresponsive on Safari

### ISSUE THREAD

**Issue by JamesM131** [r-lib/pak#399]
This is probably a safari issue so feel free to close straight away, but just wanted to flag it for your knowledge. When visiting the pak repo on GitHub my safari window will freeze up and I will need to force close it (activity monitor reports near 100% cpu usage). This happens repeatedly after multiple restarts of my computer and hasn't ocurred on any other site or GitHub repo. The pkgdown documentation home page slows safari right down and is very laggy with high reported cpu, but doesn't become unresponsive.

There is no problem when I access the site in chrome so it isn't a critical issue, but just causes issues when I have to kill other open tabs because I forgot I couldn't open this page.

Anyway, bit of a weird one and not really an issue with the package itself so I hope its okay to post here. Thanks for the great work you do.

Hardware + Software Details: 
Intel MBP 2016
macOS Monterey 12.4
Safari Version 15.5 (17613.2.7.1.8)

**Comment by gaborcsardi** [comment]
Looks ok from Safari here, barely any cpu usage. Version 15.4 (17613.1.17.1.13). I doubt that it is the Safari version, though. Maybe you have some extensions? Only the pain page with the animated SVG is problematic, or the other pages as well, the ones without SVGs?

<img width="1392" alt="Screen Shot 2022-08-01 at 9 05 30 AM" src="https://user-images.githubusercontent.com/660288/182091960-fb2cce8c-544d-42f2-ba7f-fbad536d18a3.png">

**Comment by JamesM131** [comment]
I'm not running any extensions and it seems to be just the README for the pkgdown site and GitHub. I ran some Safari performance timelines in a private window of just scrolling to the bottom of the page then back up for 3 pages below.

It might just be an issue with my machine, but it is consistently reproducible. 

![Screen Shot 2022-08-04 at 11 04 44 am](https://user-images.githubusercontent.com/20141156/182741415-649f1edf-9ae4-4d48-a443-3dad5acf7169.png)
![Screen Shot 2022-08-04 at 11 05 35 am](https://user-images.githubusercontent.com/20141156/182741426-30859dfc-8963-4061-b064-066d9839a098.png)
![Screen Shot 2022-08-04 at 11 06 42 am](https://user-images.githubusercontent.com/20141156/182741431-6fefd27a-f37b-462c-9b39-4aae410651db.png)
.

**Comment by gaborcsardi** [comment]
I think Safari is just not very good at playing SVG animation. Not sure what we could do about this, other browsers are fine, and I don't think we can tell GitHub not to show the SVG on Safari.

**Comment by JamesM131** [comment]
No worries, not really an issue so I'll close. Just wanted to bring to attention in case it was an easy fix or broader problem.
