### ISSUE TITLE
offer helper for outdated apt-get

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pak#401]
when you haven't recently run `apt-get update`, `local_system_requirements()` and friends can fail with something like:

```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I think this is because `local_system_requirements()` doesn't itself call `apt-get update`, and RSPM returns probably don't ever include it either.
That makes sense, because `apt-get update` entails a global side effect which users might not want or anticipate.

On the other hand, it's easy to stub your toe on this especially inside cached docker images. 
And it's repetitive to have add a bunch of `apt-get update`s all over the `Dockerfile`s.

Proposed solutions (if I'm even right about this):

- offer a an additional `update-apt` argument?
- add to the documentation?

(Happy to draft a PR)

**Comment by gaborcsardi** [comment]
pak now calls `apt-get update` automatically.
