### ISSUE TITLE
Discrepancy between installed package versions and lockfile

### ISSUE THREAD

**Issue by ATpoint** [r-lib/pak#402]
I just noticed discrepancy between the versions of packages installed by pak and the version it prints to the lockfile.

For example:

```
> package.version("xfun")
[1] "0.31"
```

but in the lock file created in the same session:

```
atpoint@eep036 R % grep 'xfun' pak_lock.txt 
      "dependencies": ["htmltools", "knitr", "rmarkdown", "jquerylib", "xfun", "tinytex", "yaml"],
      "dependencies": ["xfun"],
      "dependencies": ["evaluate", "highr", "stringr", "yaml", "xfun"],
      "dependencies": ["xfun"],
      "dependencies": ["bslib", "evaluate", "htmltools", "jquerylib", "jsonlite", "knitr", "stringr", "tinytex", "xfun", "yaml"],
      "ref": "xfun",
      "package": "xfun",
        "RemotePkgRef": "xfun",
        "RemoteRef": "xfun",
      "sources": ["https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/xfun_0.32.tar.gz", "https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/Archive/xfun_0.32.tar.gz"],
      "target": "src/contrib/xfun_0.32.tar.gz",
```

The way I installed packages a while back was to make a vector with package names first like `to_install <- c("packageA", "packageB")` and then use `pak::pkg_install(to_install)`. Lockfile via `pak::lockfile_create(lockfile="/r_user_lib/pak_lock.txt", pkg=unique(c(to_install)))`.

Maybe I am just missing something obvious but how do I pin package versions to the ones being installed? It seems pak is locking the most current version available on CRAN/Bioc etc?

**Comment by gaborcsardi** [comment]
Yes, a pack lockfile is not like a lockfile in other languages, because of the peculiarities of the R package repositories.

If you want to pin certain package versions, then you are probably looking for a tool like renv?

**Comment by ATpoint** [comment]
Thanks for the super fast reply. I was actually ditching renv because of both speed (serial compilation) and suboptimal behaviour inside Docker containers, but that is not a problem I need to bother you with. I was assuming that renv lock was conceptually identical to pak lock, which is simply not the case, so never mind :)

**Comment by gaborcsardi** [comment]
I am hoping to improve the lockfile behavior in pak, and also have plans on supporting renv lockfiles in pak, so check back here for newer pak releases.
