### ISSUE TITLE
{pak} should advertise the use of binaries when using RSPM binaries?

### ISSUE THREAD

**Issue by pat-s** [r-lib/pak#408]
When installing RSPM binaries on Linux, it looks like as if {pak} might download the source of the package due to the line

```r
✓ Got brew 1.0-7 (source) (75.66 kB)
```

This is  not true as the RSPM binary is downloaded and installed (which can be verified by installing a package like {stringi} which would otherwise cause a long install time when installed from source). However, this line above causes confusion and maybe {pak} could output something like

```r
✓ Got brew 1.0-7 (binary) (75.66 kB)
```

instead?

Maybe this is even not caused by {pak} but because RSPM puts the binary tarballs below `src/` instead of `binary/`?
Maybe this is because CRAN builds no binary pkgs and therefore on Linux there is no `binary/` dir?
https://packagemanager.rstudio.com/client/#/repos/1/packages/brew

```
BINARY FILE FOR [UBUNTU 20.04 (FOCAL)](https://packagemanager.rstudio.com/client/) AND [R 4.2](https://packagemanager.rstudio.com/client/)
https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/brew_1.0-7.tar.gz?r_version=4.2
```

```r
pak::pkg_install("brew")
 
→ Will install 1 package.
→ Will download 1 CRAN package (55.52 kB).
+ brew   1.0-7 [bld][dl] (55.52 kB)
ℹ Getting 1 pkg (55.52 kB)
✓ Got brew 1.0-7 (source) (75.66 kB)                               
✓ Downloaded 1 package (75.66 kB)in 1.4s                             
ℹ Building brew 1.0-7
✓ Built brew 1.0-7 (490ms)                                  
✓ Installed brew 1.0-7  (36ms)                                
✓ 1 pkg: added 1, dld 1 (75.66 kB) [2.8s] 

getOption("repos")
                                                                RSPM 
"https://packagemanager.rstudio.com/cran/__linux__/focal/2022-06-23"
```

**Comment by gaborcsardi** [comment]
Yes, this is part of https://github.com/r-lib/pkgdepends/issues/186
