### ISSUE TITLE
Error when requesting system requirements

### ISSUE THREAD

**Issue by SvenVw** [r-lib/pak#411]
When using `pak` to request the system dependencies with the function `pkg_system_requirements()` the function throws an error. I have tried this for multiple packages ('units', 'data.table', 'plumber', 'pak') and they all give the same error.

For example:
`pak::pkg_system_requirements('pak')` returns: 

``
Error: 
! error in pak subprocess
Caused by error in `asNamespace("pak")$system_requirements_internal(...)`:
! Unsupported system
Type .Last.error to see the more details.
``

.Last eror gives: 

```
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `asNamespace("pak")$system_requirements_internal(...)`:
! Unsupported system
---
Backtrace:
1. pak::pkg_system_requirements("pak")
2. pak:::remote(function(...) asNamespace("pak")$system_requirements_internal(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. asNamespace("pak")$system_requirements_internal(...)
3. base::stop(data$error)
4. | base::.handleSimpleError(function (e) …
5. global h(simpleError(msg, call))
```

sessionInfo:

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pak_0.3.1

loaded via a namespace (and not attached):
[1] compiler_4.2.0  tools_4.2.0     rstudioapi_0.13
```

**Comment by gaborcsardi** [comment]
System requirements are not supported on Windows.

**Comment by SvenVw** [comment]
Ok, thanks for letting me know. However, according to the documentation of `pkg_system_requirements` the list of supported operating systems can be found at https://github.com/rstudio/r-system-requirements#operating-systems, which lists Windows from R 4.0+. So this seems to me a little bit confusing.
