### ISSUE TITLE
Certificate issues on R-devel (GHA)

### ISSUE THREAD

**Issue by pat-s** [r-lib/pak#415]
In some CI runs of mine (across different projects), I see constant `ca-bundle.crt` related issues since some days. Only affects the R-devel runs.

https://github.com/ropensci/tic/actions/runs/3095377738/jobs/5009725286#step:9:1451

Any idea where these might origin from? Not sure if its related to {pak}, R-devel or GHA in the first place.

**Comment by gaborcsardi** [comment]
It seems that you overwrite pak with the CRAN version, and this causes the problem: https://github.com/ropensci/tic/actions/runs/3095377738/jobs/5009725286#step:9:1376

**Comment by gaborcsardi** [comment]
A workaround is to avoid running old pak with the files of the newly installed pak in the same R session. So before
```
ℹ Running stage 'install': step_install_deps()
```
you could start a new R session.

**Comment by pat-s** [comment]
Thanks! I've know understood the issue.

I could also see that if `install.packages('pak', repos = 'https://r-lib.github.io/p/pak/stable')` would install the latest pak release, i.e. 0.3.1 at this time, this might already help? 

Are the binaries and aliases automatically updated after a new {pak} release or is some delay expected (as it exists right now)? Otherwise I might need to fall back to the CRAN repo but this won't give me a binary and hence delay the installation.

**Comment by pat-s** [comment]
I think it would already suffice if binaries for 0.3.1 would be available from here, i.e. AFAICS this would only require a manual trigger of the `build-pak-binary` workflow: https://github.com/r-lib/pak/actions/workflows/build-package.yaml

Maybe this WF could also be conditioned to run automatically for new releases?

**Comment by gaborcsardi** [comment]
Versions do not matter. Our binaries bundle the certs, the cran binaries do not.

**Comment by pat-s** [comment]
Ah thanks for the heads-up, I guess I finally understood the underlying issue now.

I don't see an "easy" fix for {tic} here. For now reinstalling {pak} from CRAN again (which adds a build delay of 1 min 20s) but no other repos than {tic} are affected for now.
I might need to solve this in a more robust way at some point.

**Comment by gaborcsardi** [comment]
Yeah, this is a general problem on GHA and we have a pak (?) issue for it I _think_, but cannot find it now.... Packages are starting to depend on pak, and in general you cannot expect pak to work if it is overwriting itself with a potentially different version, plus there is the DLL locking issue on Windows, etc.

I think the solution will be to install pak into a different library (e.g. the system library?) on GHA. Then it will install the other pak instance into the user library, as it is happening now, and that copy will be used for testing.

As for the build time, if you use RSPM, they should have pak binaries.
