### ISSUE TITLE
`{pak}` not available for `R 3.2`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pak#417]
From its CRAN page, I gather that `{pak}` [supports](https://cran.r-project.org/web/packages/pak/index.html) `R >= 3.2`.

But, while trying to R CMD check `{lintr}` for this R version, the workflow fails with the error (as can be seen [here](https://github.com/r-lib/lintr/actions/runs/3115097727/jobs/5051652231)):

> Error: Error in loadNamespace(name) : there is no package called ‘pak’

So, is `{pak}` actually not available for `R 3.2`?

**Comment by gaborcsardi** [comment]
No, sorry, it need R 3.4 now.

**Comment by IndrajeetPatil** [comment]
Ah, okay, good to know. 

I don't know if you want to keep this open as a reminder to change the version in `DESCRIPTION` or close it. Fine either way.

**Comment by gaborcsardi** [comment]
This has been updated I believe.
