### ISSUE TITLE
Debian support?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pak#418]
I tried to use pak on Debian and was surprised to find that system library installation is not supported.

```r
pak::pkg_system_requirements("curl", "debian", "11")
#> Error: 'arg' should be one of “ubuntu”, “centos”, “redhat”, “opensuse”, “sle”
#> Type .Last.error.trace to see where the error occurred
```

I think this is due to the fact that there is no information about Debian in the following repository, which seems rather odd since Ubuntu and Debian are not usually distinguished in the error messages that appear when installing R packages.
https://github.com/rstudio/r-system-requirements

**Comment by eitsupi** [comment]
Oh, Debian seems to have been recently removed. rstudio/r-system-requirements#107

**Comment by eitsupi** [comment]
I am wondering if there is an option to force a change in the distribution that pak is aware of. (Related to #396)

**Comment by gaborcsardi** [comment]
Debian is fully supported now.
