### ISSUE TITLE
Subscript out of bounds when using pak with GitHub Actions

### ISSUE THREAD

**Issue by billdenney** [r-lib/pak#421]
When I try to install several GitHub packages using `pak` with GitHub actions, I get the following error:

https://github.com/nlmixr2/babelmixr2/actions/runs/3169376141/jobs/5161243116#step:5:104

The relevant GitHub actions yaml file is here:

https://github.com/nlmixr2/babelmixr2/blob/285f880fcb8902b3320d17878d584590cf41fe6c/.github/workflows/R-CMD-check.yaml#L42-L55

**Comment by gaborcsardi** [comment]
I see this interactively:
```r
❯ pak::lockfile_create(dependencies = TRUE)
✔ Updated metadata database: 1.41 MB in 3 files.
✔ Updating metadata database ... done
✖ Creating lockfile pkg.lock [4.3s]
Error:
! error in pak subprocess
Caused by error:
! Cannot install packages:
* deps::.: Can't install dependency lixoftConnectors
* lixoftConnectors: Can't find package called lixoftConnectors.
Type .Last.error to see the more details.
```

**Comment by billdenney** [comment]
Thanks!  That's helpful troubleshooting!  Is there a way to get that message to the GitHub actions log so that it's easier to find?

**Comment by gaborcsardi** [comment]
IDK why the log is different.

**Comment by billdenney** [comment]
As I looked in a bit more detail, I found that the `DESCRIPTION` file lists the needed CRAN-like repository in the `Additional_repositories` section (https://github.com/nlmixr2/babelmixr2/blob/285f880fcb8902b3320d17878d584590cf41fe6c/DESCRIPTION#L42).  Maybe there is a second feature request for `pak` to look there, too.  (I'm happy to open that as a separate issue, if that's helpful.)

**Comment by gaborcsardi** [comment]
That field is not supported, but you can add that repo to `options("repos")`.
