### ISSUE TITLE
ubuntu-latest becomes 22.04, and pak don't support

### ISSUE THREAD

**Issue by kongdd** [r-lib/pak#432]
As described in the titie, the following is an example:

https://github.com/rpkgs/rtrend/blob/c3d8e4b212022f8f2d1b4223cf7c0279998fa309/.github/workflows/R-CMD-check.yaml#L26-L32

https://github.com/rpkgs/rtrend/actions/runs/3407745859/jobs/5901085104

![image](https://user-images.githubusercontent.com/9815742/203223080-4239f120-eada-465c-83c9-87dfead26bdc.png)

**Comment by gaborcsardi** [comment]
Hi, I suggest you update your workflow according to the latest examples: https://github.com/r-lib/actions/blob/30e67efa0d3e82f278478ae5f1bd50271e522334/examples/check-standard.yaml#L42-L45

**Comment by kongdd** [comment]
Thank you. It works

**Comment by kongdd** [comment]
Just one more question. I got the error in the latest R CMD check: `Error: R CMD check found WARNINGs`.
I want to ignore warnings and treat warnings as safe. Any idea how to make it?

**Comment by gaborcsardi** [comment]
I think `check-r-package` has a parameter for that: https://github.com/r-lib/actions/tree/v2/check-r-package

**Comment by kongdd** [comment]
Thank you. Got it.
