### ISSUE TITLE
`pkg_download()` from GitHub repo

### ISSUE THREAD

**Issue by mikkmart** [r-lib/pak#434]
I’m trying to download source tarballs from GitHub repos with `pkg_download()`. However, only a `.tar.gz-t` file is downloaded. Is this intended? If so, how do I use the downloaded file?

``` r
pak::pkg_download("r-lib/pak", platforms = "source")
#> ℹ Getting 1 pkg with unknown size
#> ℹ Getting 1 pkg with unknown size
#> ✔ Got pak 0.3.1.9000 (source) (182.13 kB)
#> ✔ Got pak 0.3.1.9000 (source) (182.13 kB)
list.files("src/contrib")
#> [1] "pak_0.3.1.9000_1f1d1e4.tar.gz-t"
```

**Comment by gaborcsardi** [comment]
Yes, it is a `.tar.gz` file that is not a source package, but a package tree, i.e. the files of the repository. That's why it has a `-t` suffix.

```r
❯ dl <- pak::pkg_download("r-lib/pak", platforms = "source")
ℹ Getting 1 pkg with unknown size
✔ Cached copy of pak 0.3.1.9000 (source) is the latest build
✔ No downloads needed, all packages are cached

❯ dl$fulltarget_tree
[1] "./src/contrib/pak_0.3.1.9000_1f1d1e4.tar.gz-t"

❯ untar(dl$fulltarget_tree, list = TRUE)[1:10]
 [1] "r-lib-pak-1f1d1e4/"
 [2] "r-lib-pak-1f1d1e4/.Rbuildignore"
 [3] "r-lib-pak-1f1d1e4/.github/"
 [4] "r-lib-pak-1f1d1e4/.github/.gitignore"
 [5] "r-lib-pak-1f1d1e4/.github/workflows/"
 [6] "r-lib-pak-1f1d1e4/.github/workflows/R-CMD-check.yaml"
 [7] "r-lib-pak-1f1d1e4/.github/workflows/build-package.yaml"
 [8] "r-lib-pak-1f1d1e4/.github/workflows/build.yaml"
 [9] "r-lib-pak-1f1d1e4/.github/workflows/linux-builder-containers.yaml"
[10] "r-lib-pak-1f1d1e4/.github/workflows/nightly.yaml"
```

This will be improved eventually, and possibly the file will have a different name. Nevertheless `$fulltarget_tree` will point to the right file.

**Comment by mikkmart** [comment]
Okay, thanks! So I can check both `$fulltarget` and `$fulltarget_tree` to see which exists to determine if I got a source tree or a source package. Then if I got a tree then `untar()` and `R CMD build` to get the source package. Is that right?

**Comment by gaborcsardi** [comment]
Yes, exactly.

**Comment by mikkmart** [comment]
Great, thanks for the help!
