### ISSUE TITLE
How to use pak & renv together

### ISSUE THREAD

**Issue by telegott** [r-lib/pak#436]
I have a project that should be deployed as a docker container, that means:

- I need an isolated library for development
- I need a way to fix package versions that I use during development
- Exactly these versions should install in the container, if possible from a plain lockfile, without recreating any isolated environment
- The package installation in the container should be fast.

I do _not_ want to follow the R package structure, since I want to use `box` and nested modules.
`renv` is not exactly speedy, which is why I wanted to try `pak`. However, if I'm correct, `pak` does not setup a per-project library like `renv` does.

Using `pak` _only_ in the container is not possible either, since it can't install from `renv.lock`.

I was wondering whether it's possible to use both together:

- `renv::init(bare=TRUE)` to set up the project library
- install `pak`
- add a package to `DESCRIPTION`
- do `pak::lockfile_create()` to snapshot the package mentioned in `DESCRIPTION` and their exact versions
- copy that lockfile to the container, and to `pak::lockfile_install()` in the container

What would be the recommended approach to have something similar to `poetry`, a file that describes the project dependencies, an isolated library, a lockfile, and as bare-bones as possible recreation in an isolated environment like docker?

**Comment by gaborcsardi** [comment]
There is no current recommended approach to use pak and renv together, you are a pioneer here, for better or worse.

pak will potentially be able to install packages from an renv lockfile: #343. I guess that would solve most (all?) of your problems.

**Comment by telegott** [comment]
@gaborcsardi thanks for your answer! So I get it right that `pak` can't replace `renv` in terms of local development per-project library isolation?

**Comment by gaborcsardi** [comment]
Not currently, no. pak does not do anything with libraries currently. It installs into the first library on `.libPaths()` by default. So if you set up your libraries manually or with another tool, then pak will happily use the default library.

**Comment by telegott** [comment]
@gaborcsardi thanks, will look into this!

**Comment by gaborcsardi** [comment]
renv now supports pak for installing packages, so I am going to close this.
