### ISSUE TITLE
How to debug pak?

### ISSUE THREAD

**Issue by jonlachmann** [r-lib/pak#446]
Hi!

I am using pak and really like how it works. However, I am running into some issues and it is a nightmare to try and create something reproducible as I somehow seem to have a strange state on some of the computers I use it on, but I have no idea how to get the state off of that computer.

Anyway, I did what I usually do and cloned the pak repo to see if I can find the problem myself. However, with all the callr stuff going on, I have no idea how to follow the execution of the code properly. Is there a recommended path to see what is going on inside for example ```pkg_install_do_plan```? Is it possible to run pak _without_ callr, i.e. sequentially for debugging?

I am having issues where I get a 
```
Error (errors.R#228): ! error in pak subprocess
Caused by error in `lock(lockfile)`:
! Cannot open lock file: Permission denied
```
error, but I have no idea what lockfile it is referencing. It would be great to be able to just print the name of the file or similar to see what seems to be the problem.

On another machine, I am getting a problem inside ```satisfies_remote``` where a remotesha field is out of bounds on a list. Here again it would be great to be able to see what is actually passed to the function.

I am happy to provide more information if needed, but some guidance on how to properly work with pak and the debugger would allow me to at least provide useful issues or even solve them.

All the best, Jon

**Comment by gaborcsardi** [comment]
pak runs pkgdepends in the subprocess, so you are better off debugging pkgdepends instead of pak.

**Comment by jonlachmann** [comment]
Thanks for the comment, I was thinking that it would be a great idea.

However, I am not even able to understand which arguments are passed to it. If I stop the debugger inside the ```remote``` function of pak, it looks as if proposal is null, which when running ```pkg_install_do_plan``` I get an error already when it tries to access the download function. When running through callr it seems to get further than that. Sorry for the un-informed questions, but I am not really used to working with callr.

Any guidance you can offer is highly appreciated.

**Comment by gaborcsardi** [comment]
What I meant was to call pkgdepends directly, without callr, like this: https://github.com/r-lib/pkgdepends/#package-installation

or if you want to use an existing lock file:
https://r-lib.github.io/pkgdepends/reference/pkg_installation_plan.html

**Comment by jonlachmann** [comment]
Thanks a lot, this really helps! Now I will try to find the error and create a proper issue or PR if I am able to fix it myself. You can close this issue if you want. It may be a good idea to have some kind of "how to debug pak issues" guide, as I found it very complicated before receiving your feedback. Anyway, thank you!

**Comment by jonlachmann** [comment]
Hi!

I think I have found a solution to my problem here, https://github.com/r-lib/pkgdepends/commit/8b4009657043351650790ef458527c1dbc812a61

I am however unsure about how to get pak to use my modified version of pkgdepends. Any advice in this direction would be very welcome. Also, should I create a PR for this?

**Comment by gaborcsardi** [comment]
> I am however unsure about how to get pak to use my modified version of pkgdepends.

1. install your version of pkgdepends
2. install dev version of pak from the git tree
3. call `pak:::create_dev_lib()`, as the install command advises you.

> I think I have found a solution to my problem here, https://github.com/r-lib/pkgdepends/commit/8b4009657043351650790ef458527c1dbc812a61

That is unlikely to be a problem, because
```r
❯ NULL[[1]][["remotesha"]]
NULL
```
so `sha2` is `NA` so we return `FALSE` already:
```
❯ pkgdepends:::is_string(NA_character_)
[1] FALSE
```

**Comment by jonlachmann** [comment]
Hmm, you are indeed correct in that. But I keep getting an error as this:
```
error in pak subprocess
Caused by error in `candidate$extra[[1]][["remotesha"]]`:
subscript out of bounds
```

I will investigate further with the new information! Thanks!

**Comment by gaborcsardi** [comment]
Well, can you print what `candidate` and `candidate$extra` are?

**Comment by jonlachmann** [comment]
Hi, sorry for the messy updates on the issue. If I install the latest version of pkgdepends (without modifications) and then install the latest version of pak, then run ```pak:::create_dev_lib()``` everything works as it should. So it seems the remotesha error may be fixed in the latest release.

However, it only works in the session where I installed everything, if I open another session I get 
```
Error in registerS3method("format", "callr_status_error", pkg_env$format.callr_status_error, : bad method
```
Both if I try to run ```pak::local_install``` before or after running ```pak:::create_dev_lib()```. Do you have any pointers to what may cause this? Thanks!

**Comment by jonlachmann** [comment]
Hi!

After installing by running 
```
Rscript -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/%s/%s/%s/%s", "devel", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
```
as per your recommendations, the issue is no longer present. I can conclude that the problems I were having are fixed in the dev version but not on the CRAN version.

Thank you for all the guidance on how to work with pak and pkgdepends. It felt very daunting at first but now I am more confident if I experience any new issues.
