### ISSUE TITLE
The `pkg_system_requirements` function does not work on Cent OS 7

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pak#451]
It seems that the `pkg_system_requirements` function does not work on Cent OS 7 (`rstudio/r-base:4.1-centos7`).
`pak` has a binary installation of the stable version.
Could it be a problem of differences due to distribution?

```r
> pkg_system_requirements("curl")
Error: 
! error in pak subprocess
Caused by error in `curl::curl_fetch_memory(req_url)`:
! error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
Type .Last.error to see the more details.
```

I get the same error after I install `ca-certificates`.

**Comment by gaborcsardi** [comment]
Note that pak does not use `pkg_system_requirements()` when installing packages and it will be deprecated in the next pak release.

**Comment by eitsupi** [comment]
> Note that pak does not use `pkg_system_requirements()` when installing packages and it will be deprecated in the next pak release.

Thanks for letting me know that, is there any other way to get a list of the system packages needed to install the R packages?

**Comment by gaborcsardi** [comment]
pak installs them automatically if you turn on sysreqs support (it is on by default on the CI): https://pak.r-lib.org/dev/reference/pak-config.html

`pak::lockfile_create()` includes the system requirements in the lockfile.

You can use pkgdepends directly to query sysreqs, but its API is not exposed in pak yet.

**Comment by eitsupi** [comment]
Thanks for your prompt reply!

I was wanting to use `pkg_system_requirements` because it did not work well when sysreqs was set to true in the shell script. (https://github.com/rocker-org/devcontainer-features/actions/runs/3812227448/jobs/6485325726#step:4:2680)
If the pkgdepends functionality can be accessed from pak I would like to use that.

I'll take a look at lockfile for now.

**Comment by gaborcsardi** [comment]
I suggest you try to fix the `sh -c apt-get install -y libcurl4-openssl-dev` command instead of handling system requirements manually. Maybe try running Docker locally if that's possible. Possibly you need an `apt-get update` first or you need `sudo`.

**Comment by eitsupi** [comment]
Thanks for your advice.
I'm sorry to say, but you are right, not running apt update was the reason it didn't work.
`CI=true` seems to be working very well.

Thanks for your advice and the development of these wonderful packages.

**Comment by gaborcsardi** [comment]
No worries, pak should call `apt-get update` ideally. Right now we just run what the RStudio/Posit Package Manager tells us, so we don't know how to update the package metadata. We'll improve this eventually.

It also should have a better error message.
