### ISSUE TITLE
pkg_deps() not giving me the LinkingTo dependencies

### ISSUE THREAD

**Issue by daattali** [r-lib/pak#457]
I want to figure out all the package dependencies that a specific package needs, so that I can download the source for all those packages and later install them on a computer with no internet.

As a simple exapmle of the issue: package {anytime} has a `LinkingTo` dependency on {BH}. When I call `pak::pkg_deps("anytime")` or even `pak::pkg_deps("anytime", dependencies = "LinkingTo")` I don't get {BH} in the results.
 
I suspect this might behappening because I'm calling the function while on a Windows machine. If this is the case, then the function needs to be more clear that it only lists dependencies for the current platform, because my assumption was that I can use this function to simply go through the DESCRIPTION files of all dependencies, recursively, and simply list them.

**Comment by gaborcsardi** [comment]
Set the platform to "source", see https://pak.r-lib.org/reference/pak-config.html. E.g.

```r
❯ pak::pkg_deps_tree("anytime")
anytime 0.3.9 ✨ ⬇ (1.13 MB)
└─Rcpp 1.0.10 ✨ ⬇ (3.27 MB)

Key:  ✨ new |  ⬇ download
```

```r
❯ options(pkg.platforms = "source")
❯ pak::pkg_deps_tree("anytime")
✔ Loading metadata database ... done
anytime 0.3.9 ✨👷🏻‍♀️🔧 ⬇ (348.90 kB)
├─Rcpp 1.0.10 ✨👷🏻‍♀️🔧 ⬇ (2.94 MB)
└─BH 1.81.0-1 ✨👷🏻‍♀️ ⬇ (13.94 MB)

Key:  ✨ new |  ⬇ download | 👷🏻‍♀️ build | 🔧 compile
```

**Comment by daattali** [comment]
Ah, I was looking for a parameter for that. Would `platform` be a parameter you'd consider adding?

**Comment by gaborcsardi** [comment]
I don't want to have a hundred parameters, so at this point, no. Or at least not yet.

**Comment by gaborcsardi** [comment]
OTOH we'll have a generic "config" parameter at some point, I think.

**Comment by daattali** [comment]
I closed the issue, but I do think it would be worthwhile to add some information to the function documentation, saying that additional options can be used as per the package config.

**Comment by gaborcsardi** [comment]
That is true for all functions, though, so it seems a bit redundant.

**Comment by daattali** [comment]
I suppose it's a matter of whether a documentation for a function should be self-contained or not. It's subjective, but I personally think that it should; I don't expect to have to read the manual for a package if I just want to use one function from it if the function seems simple enough. I won't open an issue for that or press on this any longer, but wanted to offer my perspective as a user who found the documentation lacking.
