### ISSUE TITLE
Version behaviour for older R versions 

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#46]
Should it behave like install.packages and only give you the binary version? (Which might be very out of date) Should it warn that a newer version is available? Should I prompt? Should it use declared version requirements?

**Comment by gaborcsardi** [comment]
`pkgdepends` currently always considers both the binary (if available) and the source versions. The default behavior (`upgrade = FALSE`) only uses the source version if the binary does not satisfy the requirements. (Or causes a conflict downstream.)

If `upgrade = TRUE` then the newer version is considered, source or binary. If they are the same then the binary is used. (Or the already installed version, if there is one.)

**Comment by jimhester** [comment]
The default behavior as Gabor described seems correct to me, so I think we can close this.
