### ISSUE TITLE
`Could not solve package dependencies` error when trying to install github dependency rather than cran version

### ISSUE THREAD

**Issue by billdenney** [r-lib/pak#460]
The issue is illustrated here:

https://github.com/nlmixr2/rxode2/actions/runs/4034485677/jobs/6935733544#step:6:150

We want to install the github version of the package `rxode2parse` rather than the CRAN version, so we are using the following in our GitHub actions:

https://github.com/nlmixr2/rxode2/blob/29ccacdacb66d51f50ec3872ede162b8d109f107/.github/workflows/R-CMD-check.yaml#L51-L62

I would have thought that the manual installation of the GitHub version there would override the automatic installation of the CRAN version, but that does not seem to be the case.

Is there a better installation method for GitHub actions to use a certain set of packages from GitHub instead of CRAN?

(FYI, @mattfidler)

**Comment by mattfidler** [comment]
This is because `dparser` on CRAN is the wrong version for `rxode2parse`.  Simply put the `dparser` github dependency to solve this issue.
