### ISSUE TITLE
pak not installing remote package from GitHub

### ISSUE THREAD

**Issue by isaactpetersen** [r-lib/pak#465]
I'm using GitHub Actions (`r-lib/actions/setup-r-dependencies`) to install R packages via `pak` from a `DESCRIPTION` file. However, I'm having trouble installing a remote package from GitHub. Two of the remote GitHub packages install fine, but one of them does not. It formerly installed fine, so I'm not sure what the issue is. I don't see any info in the logs indicating that the package even attempted to install (or failed).

Here is my `DESCRIPTION` file:
https://github.com/isaactpetersen/Principles-Psychological-Assessment/blob/main/DESCRIPTION

Specifically, `evwalz/uroc` and `ddueber/dmacs` install fine, whereas `DevPsyLab/petersenlab` does not seem to install.

Here is my workflow file:
https://github.com/isaactpetersen/Principles-Psychological-Assessment/blob/main/.github/workflows/deploy_bookdown.yml

My log file is here:
https://github.com/isaactpetersen/Principles-Psychological-Assessment/actions/runs/4336453056/jobs/7571750375#step:7:121

I'm a bit new to `pak`, so any help would be greatly appreciated.

**Comment by gaborcsardi** [comment]
You don't actually import that package. You need to put it into the `Imports` field as well.

**Comment by isaactpetersen** [comment]
That perfectly answers my question--thanks!
