### ISSUE TITLE
Operator invalid for atomic vectors, r$version

### ISSUE THREAD

**Issue by jonlachmann** [r-lib/pak#474]
Hi!

I have been using pak on the devel version as I am otherwise experiencing issues with packages that I some of the time want to download from github, and some of the time from CRAN (i.e. to get the latest version, but then go back to CRAN). Yesterday the latest pak devel version worked great, but today I get the error below. It seems to be related to the ppm adjustments made.

To solve this in the meantime, I wonder:

Is there a new stable version of pak planned for release to CRAN? At the moment the issues I am having with packages that are sometimes on CRAN and sometimes on github makes the current CRAN version problematic to use.

Is it possible to get yesterdays devel build somehow?

```
✔ Loading metadata database ... done
Error: 
! error in pak subprocess
Caused by error in `r$version`:
! $ operator is invalid for atomic vectors
---
Backtrace:
1. pak::local_install(".", ask = F, upgrade = F)
2. pak:::remote(function(...) get("local_install_make_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("local_install_make_plan", asNamespace("pak"))(...)
 3. pak:::pkg_install_make_plan(pkg, lib, upgrade, ask, start, dependencies, …
 4. prop$solve()
 5. private$plan$solve(policy = private$policy)
 6. pkgdepends:::pkgplan_solve(self, private, match.arg(policy))
 7. private$create_lp_problem(pkgs, policy)
 8. pkgdepends:::pkgplan__create_lp_problem(self, private, pkgs, policy)
 9. pkgdepends:::pkgplan_i_create_lp_problem(pkgs, private$config, policy)
10. pkgdepends:::pkgplan_i_lp_latest_direct(lp)
11. pkgdepends:::vlapply(lp$pkgs$remote, function(r) !is.null(r$version) && r$version != …
12. base::vapply(X, FUN, FUN.VALUE = logical(1), ...)
13. local FUN(X[[i]], ...)
14. base::.handleSimpleError(function (e) …
15. global h(simpleError(msg, call))
Execution halted
```

**Comment by jonlachmann** [comment]
> Can you show a reproducible example? E.g. is the package you are experiencing this with public?

Hi! The problem is that the package this is occurring with is proprietary... I can try to debug it to see if I can get more information, to see if it is possible to build a minimal reproducible example.

Is it possible to access older versions of the devel prebuilts?

**Comment by jonlachmann** [comment]
Thanks, then I can probably solve my immediate issue.

I have managed to narrow down the problem a bit. The issue is that when I arrive at this line https://github.com/r-lib/pkgdepends/blob/bd4b34097fe15f7905d2c97c001a21eb13903996/R/solve.R#L470, some of ```lp$pkgs$remote``` are ```NA```.

What are the implications of remote being NA here? Is it something that is expected to happen or is it something that is off?

I am not sure I can post all the dependencies here, maybe I could send you a list in private? It is also a bit strange, since I get the error on some computers but not all.

**Comment by gaborcsardi** [comment]
I don't think `lp$pkgs$remote` should ever be `NA`.

**Comment by gaborcsardi** [comment]
Re dependencies, sure, it is file in private as well.

**Comment by gaborcsardi** [comment]
What is your OS and R version?
Does yesterday's build really fix this issue?

**Comment by jonlachmann** [comment]
I sent you an email with all the deps.

Running the build from yesterday seems to work, yes. I am thinking it does not have the row from pkgdepends which is causing the issue.

What does ```lp$pkgs$remote``` signify? I am trying to understand what the purpose of it is, so I can better assist the debugging!

I am on the machines that are having trouble running Ubuntu 20, and R 4.2.1.

**Comment by gaborcsardi** [comment]
Let me build new pak devel builds. I assume you are on x86_64.

**Comment by jonlachmann** [comment]
> Let me build new pak devel builds. I assume you are on x86_64.

Yes, correct!

**Comment by jonlachmann** [comment]
> OK, should be good now.

Can confirm that it works now!
