### ISSUE TITLE
pak::lockfile_create() fails when using depends for package using any other syntax than ({package_name}>=version)

### ISSUE THREAD

**Issue by thomasyu888** [r-lib/pak#503]
Here is the respository: https://github.com/Sage-Bionetworks/synapser/tree/update-client-version.    I discovered this issue when trying to use `r-lib/actions/setup-r-dependencies@v2`
```
> pak::lockfile_create()
✖ Creating lockfile pkg.lock [423ms]                                        
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* deps::.: Can't install dependency reticulate (== 1.28)
```

```
> pak::lockfile_create()
✔ Updated metadata database: 5.29 MB in 12 files.                         
✔ Updating metadata database ... done                                     
✖ Creating lockfile pkg.lock [14.4s]                                       
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* deps::.: Can't install dependency reticulate (<= 1.28)
```

**Comment by gaborcsardi** [comment]
This is not a bug in pak, but it is just how CRAN metadata is organized: it does not contain older versions of reticuate, only the latest 1.29 version. R packages do not properly support versioned dependencies.

If you need to depend on a specific older version, you can use the `Remotes` field and the `pkg@version` syntax, see https://pak.r-lib.org/reference/pak_package_sources.html#the-remotes-field

**Comment by thomasyu888** [comment]
Thanks @gaborcsardi for the explanation!  Your solution worked perfectly! Closing this.
