### ISSUE TITLE
Problem with installing openrouteservice package

### ISSUE THREAD

**Issue by pascalgulikers** [r-lib/pak#515]
Hello, we're using PAK als our R package dependency solver.
No matter what I try, I can't get openrouteservice package installed.

For example:

```
Depends:
  openrouteservice=github::/GIScience/openrouteservice
```

Results in:

```
pak::pkg_install("~/test")
Error:                                                                                            
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* local::~/test: Can't install dependency openrouteservice=github::GIScience/openrouteservice-r
Type .Last.error to see the more details.
```

See: https://pak.r-lib.org/reference/pak_package_sources.html
Is there a working example for how to implement openrouteservice as a dependency in a package (e.g. DESCRIPTION file)?

**Comment by gaborcsardi** [comment]
Hi, https://github.com/GIScience/openrouteservice is not an R package AFAICT.

**Comment by pascalgulikers** [comment]
I'm sorry, typo, I meant https://github.com/GIScience/openrouteservice-r

**Comment by gaborcsardi** [comment]
This is the correct syntax:
```
Imports:
    openrouteservice
```
...
```
Remotes:
    openrouteservice=github::GIScience/openrouteservice-r
```

See the pak docs or https://r-pkgs.org/dependencies-in-practice.html#depending-on-the-development-version-of-a-package

**Comment by pascalgulikers** [comment]
That works! Thanks a lot!!
