### ISSUE TITLE
Disable apt-get "helper"

### ISSUE THREAD

**Issue by gdevenyi** [r-lib/pak#530]
I do not want pak trying to modify my system. How can I disable this helper trying to run `apt-get`

**Comment by gaborcsardi** [comment]
Set the `PKG_SYSREQS=false` env var, see https://pak.r-lib.org/dev/reference/pak-config.html#pak-configuration

**Comment by gdevenyi** [comment]
Ctrl-F "apt-get" does not show up in that documentation.

**Comment by gaborcsardi** [comment]
See also https://pak.r-lib.org/reference/sysreqs.html

We should probably also add a note to the output about turning sysreqs off, plus stop for confirmation if R is running in interactive mode.
