### ISSUE TITLE
How does pak::pkg_deps (pkg_deps_tree, pkg_deps_explain) discover the function dependencies?

### ISSUE THREAD

**Issue by vertesy** [r-lib/pak#564]
Hello,

Thanks for the cool library! I am trying to use `pak` to find all, function level dependencies across packages (`pkg_deps_explain`). Not fully successful yet:

1) How does pak::pkg_deps (pkg_deps_tree) discover the function dependencies?
Does it rely on `package::fun` or on `@importFrom` statements?

2) Is it possible to use it (or do you know of an alternative function/package) for functions that had none of those declarations?
> This happens when pacX has `Depends: pacY` declaration in `DESCRIPTION` so functions of `pacY` are ( can be) called directly within `pacX`. 

Thanks a lot!

**Comment by gaborcsardi** [comment]
pak deals with package dependencies, as declared in the `DESCRIPTION` file, it does not deal with functions or namespaces at all.

**Comment by vertesy** [comment]
Ok, thanks a lot Gabor! 
I guess it takes Depends and Imports? Or also Suggests and Enhances?

**Comment by gaborcsardi** [comment]
See the `dependencies` arguments, and its possible values: https://r-lib.github.io/pkgdepends/reference/as_pkg_dependencies.html

**Comment by vertesy** [comment]
great, thank you!
