### ISSUE TITLE
Weird issue with prettyunits on GHA

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pak#568]
https://github.com/krlmlr/bindrcpp/actions/runs/7108392065/job/19359651833#step:6:4003

```
! error in pak subprocess
  Caused by error in `loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])`:
  ! there is no package called ‘prettyunits’
```

Does this ring a bell? There's only one repo where I'm seeing this, couldn't replicate.

**Comment by krlmlr** [comment]
https://github.com/krlmlr/bindrcpp/pull/10

**Comment by krlmlr** [comment]
Stable pak looks good. Going to devel pak in the same PR to double-check.

**Comment by krlmlr** [comment]
Works now. I'll see if this works in the nightly run on the main branch.

**Comment by krlmlr** [comment]
The issue persists in the nightly run: https://github.com/krlmlr/bindrcpp/actions/runs/7122012607/job/19392351925 .

Can you work with that? I've invited you to the repo. Happy to provide more context if needed.

**Comment by gaborcsardi** [comment]
This is fixed by https://github.com/r-lib/pkgdepends/commit/fa202b03e7b7832776433cac0dceafb4a4590a60 I believe. I'll build Linux binary packages now, the rest will be built overnight.

**Comment by krlmlr** [comment]
Thanks! I'll watch my nightly CI/CD runs.

**Comment by gaborcsardi** [comment]
I believe that this is fixed now.

**Comment by krlmlr** [comment]
Thanks, confirmed!
