### ISSUE TITLE
Error installing private git repo with ssh url

### ISSUE THREAD

**Issue by m-muecke** [r-lib/pak#569]
I'm getting the following error when trying to install a private git repo with a ssh URL (substituted r-lib/pak as the url for the example, but getting the same error with a private repo hosted on Gitea). The error doesn't occur when I run `remotes::install_git` instead.

``` r
pak::pak("git::git@github.com:r-lib/pak.git")
#> Error: ! error in pak subprocess
#> Caused by error: 
#> ! Could not solve package dependencies:
#> * git::git@github.com:r-lib/pak.git: ! pkgdepends resolution error for git::git@github.com:r-lib/pak.git.
#> Caused by error: 
#> ! Failed to download 'DESCRIPTION' from git repo at
#> <://git@github.com:r-lib/pak.git>.
#> Caused by error in `(function (e) …`:
#> ! URL rejected: Port number was not a decimal number between 0 and 65535
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by m-muecke** [comment]
I'm getting the same error for the private repo hosted on Gitea with HTTPS, whereas I'm not getting an error with remotes.

**Comment by m-muecke** [comment]
``` r
pak::pak("git::https://gitea.blank.de/repl/replraw.git")
#> Error: ! error in pak subprocess
#> Caused by error: 
#> ! Could not solve package dependencies:
#> * git::https://gitea.blank.de/repl/replraw.git: ! pkgdepends resolution error for
#> git::https://gitea.blank.de/repl/replraw.git.
#> Caused by error: 
#> ! Failed to download 'DESCRIPTION' from git repo at
#> <https://gitea.blank.de/repl/replraw.git>.
#> Caused by error in `(function (e) …`:
#> ! URL rejected: Port number was not a decimal number between 0 and 65535
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
IS it possible that your git config still uses the ssh url, and that is used when pak is trying to get the credentials from the git credential store?

E.g. does
```
gitcreds::gitcreds_get(url = "https://...")
```
work?

**Comment by m-muecke** [comment]
Getting the following:

``` r
gitcreds::gitcreds_get(url = "https://...")
#> <gitcreds>
#>   protocol: https
#>   host    : gitea...
#>   username: maximilian...
#>   password: <-- hidden -->
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
OK, I can reproduce this, and it is probably a bug in pak, unfortunately.
