### ISSUE TITLE
Install system packages through conda

### ISSUE THREAD

**Issue by mangost** [r-lib/pak#573]
Thanks all you guys for creating pak. It's awesome.

---

Using pak within R installed in conda environment must be very careful, otherwsie compiling errors are common for packages depending on devel packages (packages that provide header files and lib files). 

Here is the seneria, as for as I know
- pak install system level packages using system-level package management tools like (apt), and header/lib files will be installed into /usr/include or somewhere, instead of in the conda env
- then the R package need to be compiled, during which it will use c/cxx compiler
- however, the default compiler in conda env will be the compilor in the conda env, and will not, by default, searching header/lib files in /usr/include and other system-level dirs.
- a `not finding header file` error occurs

There are a couple of workaround:
- prevent pak to modify the system packages as mentioned in #530. But it interrupt the flow (which is why I love pak)
- change conda config. which broken the isolation 
- change env variables to use system compiler instead of the one in conda env, which still broken the isolation 
- copy/link the header/lib files, which broken the isolation and bring more confusion in the future

I prefer a solution that preserve the isolation: using conda to install system-level packages. 
What do you guys think?

---

Maybe someone would say: If I am using conda, why even bother using pak? (as #531)

Explain: pak is much better, esp on Windows (latest R on conda-forge is 4.1)

Further: Why still using conda?

Explain: To use some python packages cooperating with R, and to switch env quickly (such as radian is automatically set up when I switch to the companian env). 

----

So is it possible or support conda? Or is there a solution/workaround?

There a few workaound that I am thinking about
- alias `apt/yum` into some script that call conda, and  (in conda env profile) alias R/radian into some script that do that job
- branching the source and add a platform named conda with `install_command` changed

---

It will be much helpful (to me and possibly those using conda) if pak could install system-level packages via conda.

**Comment by gaborcsardi** [comment]
I agree that it would be nice, but unfortunately the situation still the same as in the referenced issue. conda already supports installing system requirements for R packages, even though this means using somewhat older R and R package versions. 

The main issue is that we can't install system packages through conda, because we don't know what those packages are. We have a manually curated database for the required packages on supported Linux distros, but we don't have that for conda, and it seems to me creating and maintaining such a thing for conda would be very hard, if at all possible.

**Comment by mangost** [comment]
The issue also exists when trying to mannually install system packages in conda, eg, I does not find something like fftw-devel at https://anaconda.org/ .

Is it possible that the community maintain the mapping: r-deps --> conda package? 

I think the effort would be much lesser than conda-forge, which is also maintained by community and is very large and useful now. 

If there will be, then I am willing to make contribution now:

fftw3 --> conda-forge::fftw

**Comment by gaborcsardi** [comment]
Maybe. You'd need to add support for conda in this repo: https://github.com/r-hub/r-system-requirements (or ideally its upstream), and also add detection of conda somewhere here: https://github.com/r-lib/pkgcache/blob/main/R/platform.R and/or here: https://github.com/r-lib/pkgcache/blob/main/R/platform-linux.R

**Comment by gaborcsardi** [comment]
OH, and also here: https://github.com/r-lib/pkgdepends/blob/main/R/sysreqs2.R#L11
Possibly other places as well....

Btw. does `conda-forge::fftw` etc. work on all OSes and conda versions? Is the installation the same with conda, mamba, miniconda, etc?

**Comment by mangost** [comment]
I see the work needed to collect and test those deps.
Thank you and your team for doing this. 
For now, I will drop my idea and try to use pak as it is designed

PS: I didn't test it on selected OSes in nake docker envs, nor with mamba or micromamba
