### ISSUE TITLE
Installing package fails

### ISSUE THREAD

**Issue by alethor** [r-lib/pak#624]
Since yesterday several of my projects pipelines have started failing and after looking around I decided to open an issue here. Looking through the job logs I can't see any changes in versions that might explain this issue.

I created a public example repo to reproduce the error here: https://gitlab.com/aleth/test-pipeline-error/-/jobs/6771023341

Here is a direct link to the job that fails: https://gitlab.com/aleth/test-pipeline-error/-/blob/main/test-package.yml?ref_type=heads

**Comment by gaborcsardi** [comment]
This is https://github.com/r-lib/pak/issues/623, see there for a workaround.

**Comment by alethor** [comment]
I get a similar error even when using the workaround: https://gitlab.com/aleth/test-pipeline-error/-/jobs/6772208324

**Comment by gaborcsardi** [comment]
Running
```
Rscript -e 'options(repos = c(PPM = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))'
```
will not set that option for future R sessions.

**Comment by gaborcsardi** [comment]
Reopened by mistake, sorry for the noise.
