### ISSUE TITLE
pak can not resolve correct package version, only tries the latest.

### ISSUE THREAD

**Issue by gongyh** [r-lib/pak#668]
Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency rstatix
  * rstatix: Can't install dependency car
  * car: Can't install dependency pbkrtest (>= 0.4-4)
  * pbkrtest: Needs R >= 4.2.0
  * rcmdcheck: dependency conflict
  * any::sessioninfo: dependency conflict

The latest version of pbkrtest (version 0.5.3) needs R 4.2.0, but not versions between 0.4-4 and 0.5.2.

more details: https://github.com/gongyh/RamanD2O/actions/runs/10154082037/job/28078611827

**Comment by gaborcsardi** [comment]
This is not a pak issue, this is how CRAN works. They typically only include the latest versions of packages in their package metadata, so that's what we work with: https://cran.r-project.org/src/contrib/PACKAGES

**Comment by HeveraletLaidCenx** [comment]
Hi, I just encountered a similar situation...

I wrote [a simple tool](https://github.com/HeveraletLaidCenx/UPPAIR) to implement a R package dependencies tree parsing and installation **including outdated version checking**. 

I'm not sure if it's good enough, but it works for me.

If anyone encounters such a scenario, you might consider giving it a try XD.

![demo](https://github.com/user-attachments/assets/00a3fe95-de0f-4d24-ad60-0d2eb816cc36)
