### ISSUE TITLE
Silent install/upgrade packages

### ISSUE THREAD

**Issue by latot** [r-lib/pak#674]
Hi! I think would be great an option for silent installs/updates for pak, only print if there is an error or similar.

Thx!

**Comment by gaborcsardi** [comment]
Use `suppressMessages()`:

```r
❯ suppressMessages(pak::pkg_install("tidyverse", lib = "/tmp/lib2"))
❯ suppressMessages(pak::pkg_install("tidyverse2", lib = "/tmp/lib2"))
Error:
! error in pak subprocess
Caused by error:
! Could not solve package dependencies:
* tidyverse2: Can't find package called tidyverse2.
Type .Last.error to see the more details.
```

**Comment by latot** [comment]
Hi! @gaborcsardi I know there exists that utility, the issue is that is silence a lot of things... far from ideal.

I agree still is a simple solution.
