### ISSUE TITLE
`sysreqs` is not resolved correctly from a package published about 3 days ago

### ISSUE THREAD

**Issue by zhuxr11** [r-lib/pak#692]
A package [`hypergeo2`](https://cran.r-project.org/package=hypergeo2) was published on CRAN about 3 days ago. Just now I started a github `R CMD CHECK` workflow using `pak` to set up dependencies including `hypergeo2` for another package [`cbbinom`](https://github.com/zhuxr11/cbbinom), and the system requirements of `hypergeo2` was not discovered correctly, failing to install `hypergeo2` in the workflow.

Here was what I ran just now:
```r
pak::meta_update()
#> v Updating metadata database ... done                             

pak::pkg_system_requirements("hypergeo2", "ubuntu", "20.04")
#> [1] "apt-get install -y libgmp3-dev" "apt-get install -y libmpfr-dev"

pak::pkg_deps("hypergeo2")[c("ref", "package", "repotype", "sysreqs")]
#> # A data frame: 3 x 4
#>   ref       package   repotype sysreqs
#>   <chr>     <chr>     <chr>    <chr>  
#> 1 BH        BH        cran     ""     
#> 2 hypergeo2 hypergeo2 cran     NA     
#> 3 Rcpp      Rcpp      cran     ""     
```

We see: `pak::pky_system_requirements()` found the system requirements correctly (`gmp` and `mpfr`), but `pak::pkg_deps()` (used to set up dependencies in the workflow) printed the `sysreqs` as `NA`. This happened after running `pak::meta_update()`, thus with the newest metadata database.

**Comment by gaborcsardi** [comment]
This should be fixed now: 
```r
❯ options(pkg.platforms = "source")
❯ pak::pkg_deps("hypergeo2")[c("ref", "package", "repotype", "sysreqs")]
# A data frame: 3 × 4
  ref       package   repotype sysreqs    
  <chr>     <chr>     <chr>    <chr>      
1 BH        BH        cran     ""         
2 hypergeo2 hypergeo2 cran     "gmp, mpfr"
3 Rcpp      Rcpp      cran     ""         
```

**Comment by zhuxr11** [comment]
> This should be fixed now:
> 
> ```r
> ❯ options(pkg.platforms = "source")
> ❯ pak::pkg_deps("hypergeo2")[c("ref", "package", "repotype", "sysreqs")]
> # A data frame: 3 × 4
>   ref       package   repotype sysreqs    
>   <chr>     <chr>     <chr>    <chr>      
> 1 BH        BH        cran     ""         
> 2 hypergeo2 hypergeo2 cran     "gmp, mpfr"
> 3 Rcpp      Rcpp      cran     ""         
> ```

Great, when will this update be applied to the "check-standard" github workflow? Or how can I set that in `R-CMD-CHECK.yaml`?

**Comment by gaborcsardi** [comment]
It should already work on GHA as well, no need to set anything.

**Comment by zhuxr11** [comment]
> It should already work on GHA as well, no need to set anything.

Thanks, the workflow is running smoothly now.
