### ISSUE TITLE
Difference between <pkg>?source and <pkg>=?source  ?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/pak#708]
https://github.com/r-lib/pak/blob/b940875b19b193cd271c465d03f747151a856cc3/man/chunks/FAQ.Rmd#L37-L56

These paragraphs are next to each other but I can't tell if there's any difference between `<pkg>?source` and `<pkg>?=source`

**Comment by gaborcsardi** [comment]
https://pak.r-lib.org/reference/pak_package_sources.html#parameters

**Comment by MichaelChirico** [comment]
Thanks for the reference, but sorry, the exposition is still not clear.

For example, there's a transition to discussing "downstream" packages that doesn't make much sense to me. The FAQ by contrast uses the term "dependency" -- in my mind those terms are not the same.

**Comment by gaborcsardi** [comment]
* `pkg?source` = install `pkg` from source, plus its dependencies according to the `dependencies` argument.
* `pkg=?source` = if pkg will be installed, install it from source.

**Comment by MichaelChirico** [comment]
OK so in my case for {bit64}, suppose {bit} (in `Depends:` of {bit64}) also has `Imports: pkgA`

```
bit64?source  : installs bit64, bit, and pkgA from source
bit64=?source : install bit64 from source, bit and pkgA can be installed from binary
bit?source    : bit64 might be installed from binary, bit and pkgA are installed from source
bit?=source   : bit64 and pkgA might be installed from binary, bit will be installed from source
```

Does that look right to you?

**Comment by gaborcsardi** [comment]
It does not look right. But I don't really understand what you are installing? What is the command line? Or the code that calls the action?

**Comment by MichaelChirico** [comment]
I am "just" trying to run `r-lib/actions/check-r-package`.

Plain `bit?source` did work for my purposes. I am trying to understand better in the hopes of improving the documentation with that clarity.

**Comment by MichaelChirico** [comment]
> Oh, for check-r-package this does not matter at all

Maybe I need more context. This is about the `setup-r-dependencies` step that feeds `check-r-package`.

Here I followed your advice to use `bit?source`: https://github.com/r-lib/bit64/pull/109/commits/fae213b9d873485bb59ad987dcf010f97d5564b6

The result is `R CMD check` begins to pass because the `WARNING` about mismatched "built" version for {bit} and {bit64} went away (e.g. https://github.com/r-lib/bit64/actions/runs/11464927713/job/31902265368).

I still don't really understand the impact of `=` so I can't offer any improvements as of now.
