### ISSUE TITLE
Help page on package sources is missing the good stuff

### ISSUE THREAD

**Issue by jennybc** [r-lib/pak#717]
This help topic seems like it's supposed to get its content from elsewhere, but it's not actually getting there:

https://pak.r-lib.org/reference/pak_package_sources.html

<img width="549" alt="Screenshot 2024-11-19 at 2 35 44 PM" src="https://github.com/user-attachments/assets/4cad32ed-fe41-419b-a9e4-498df0da53a9">

**Comment by gaborcsardi** [comment]
Seems like https://github.com/r-lib/pkgdown/pull/2759 broke this.
