### ISSUE TITLE
add install instructions to readme?

### ISSUE THREAD

**Issue by luisDVA** [r-lib/pak#719]
Hi! 
I've been recommending this great pkg to everyone, and I just realized that some new learners were confused and tried to install pak using pak (or copied the first piece of code in the readme which is an example for installing tibble). 

The readme could possibly include instructions to install from CRAN or a dev version from GitHub.

**Comment by gaborcsardi** [comment]
It is right there:

<img width="1120" alt="Screenshot 2024-11-26 at 10 19 20 PM" src="https://github.com/user-attachments/assets/19adcbac-577b-434e-a4d6-64bf87ea124f">

**Comment by luisDVA** [comment]
my bad! I was looking for it at the top of the readme.
Sorry!
