### ISSUE TITLE
Store multiple versions of the same pkg in the cache

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pak#77]
I think it would be neat to be able to do:

```r
pkg::pkg_install("tidyverse/dplyr")
pkg::pkg_install("cran::dplyr")
pkg::pkg_install("tidyverse/dplyr") # <- this should be instantaneous
```

and have the second install of the github version of dplyr be instantaneous. Currently it tries to reinstall the dev version from github, because it seems like only 1 version is kept in the cache at a time. I don't know where you would draw the line, but maybe having 1 dev version and 1 cran version of a package would be useful to store in the cache.

**Comment by gaborcsardi** [comment]
Yeah, it is in the cache, actually, but currently pkg always builds the source package. But this is a known issue, will be fixed soon, it requires some thinking...
