### ISSUE TITLE
Remove double namespacing?

### ISSUE THREAD

**Issue by lionel-** [r-lib/pak#88]
Unless I'm missing something, pkg is meant to be used sporadically and thus unlikely to be attached to the search path. It might be more user friendly to remove the double namespacing as `pkg::pkg_install()` is longer to type than `pkg::install()`.

**Comment by gaborcsardi** [comment]
Yeah, that would probably make sense for `pkg::install()` right now, but there are other `pkg_*` functions as well, and also `lib_*` and `local_*` functions. 

The `proj_*` functions are not exported yet, these help keeping a project based library, so I would encourage these, eventually.

Considering all this, I am just not sure that `pkg_install()` will be the _default_ installation function in the end.

**Comment by gaborcsardi** [comment]
I decided not to do this. At least not just yet. I don't have a very strong opinion, though...
