### ISSUE TITLE
Package install error: 'is_utf8_output'?

### ISSUE THREAD

**Issue by barcadad** [r-lib/pak#93]
I'm getting the following error when I try to install packages:

pak::pkg_install('tidymodels/parsnip')  #<-- or any package
i Checking for package metadata updates
v All 10 metadata files are current.                                                                                                
v Using session cached package metadata                                                                                             
Error: 'is_utf8_output' is not an exported object from 'namespace:cli'

Any suggestions to fix?  Thanks

**Comment by gaborcsardi** [comment]
Update the cli package please.

**Comment by DavisVaughan** [comment]
Just as an FYI I had this too and had to update cli, nuke the pak private library, restart R, and re-setup pak. Im not sure if it's possible, but maybe pak could be more strict about the minimum versions of packages it allows into its private library? so you don't get stuck immediately into this broken state

**Comment by gaborcsardi** [comment]
Fixed in 960f449ef12e55adb68ecdf8626615322906ae9b
